core/src/prediction/InstrumentalPredictionStrategy.cpp
core/src/prediction/InstrumentalPredictionStrategy.h
core/src/prediction/PredictionStrategy.h
core/src/prediction/QuantilePredictionStrategy.cpp
core/src/prediction/QuantilePredictionStrategy.h
core/src/prediction/RegressionPredictionStrategy.cpp
core/src/prediction/RegressionPredictionStrategy.h
core/src/prediction/collector/DefaultPredictionCollector.cpp
core/src/prediction/collector/OptimizedPredictionCollector.cpp
core/test/prediction/InstrumentalPredictionStrategyTest.cpp
core/test/prediction/QuantilePredictionStrategyTest.cpp

Pass the test sample ID to prediction methods so its observation values can be accessed.

---

core/src/forest/ForestPredictor.cpp
core/src/forest/ForestPredictor.h
core/src/forest/ForestPredictors.cpp
core/src/forest/ForestTrainer.cpp
core/src/forest/ForestTrainer.h
core/src/forest/ForestTrainers.cpp
core/src/prediction/CustomPredictionStrategy.cpp
core/src/prediction/CustomPredictionStrategy.h
core/src/prediction/DefaultPredictionStrategy.h
core/src/prediction/InstrumentalPredictionStrategy.cpp
core/src/prediction/InstrumentalPredictionStrategy.h
core/src/prediction/OptimizedPredictionStrategy.h
core/src/prediction/QuantilePredictionStrategy.cpp
core/src/prediction/QuantilePredictionStrategy.h
core/src/prediction/RegressionPredictionStrategy.cpp
core/src/prediction/RegressionPredictionStrategy.h
core/src/prediction/collector/DefaultPredictionCollector.cpp
core/src/prediction/collector/DefaultPredictionCollector.h
core/src/prediction/collector/OptimizedPredictionCollector.cpp
core/src/prediction/collector/OptimizedPredictionCollector.h
core/src/tree/TreeTrainer.cpp
core/src/tree/TreeTrainer.h
core/test/forest/ForestCharacterizationTest.cpp
core/test/forest/RegressionForestTest.cpp
core/test/prediction/InstrumentalPredictionStrategyTest.cpp
core/test/prediction/QuantilePredictionStrategyTest.cpp

Split PredictionStrategy into 'default' and 'optimized' types.

---

core/src/forest/ForestTrainers.cpp
core/src/forest/ForestTrainers.h
core/src/splitting/ProbabilitySplittingRule.cpp
core/src/splitting/ProbabilitySplittingRule.h
core/src/splitting/RegressionSplittingRule.cpp
core/src/splitting/RegressionSplittingRule.h
core/src/splitting/factory/ProbabilitySplittingRuleFactory.cpp
core/src/splitting/factory/ProbabilitySplittingRuleFactory.h
core/src/splitting/factory/RegressionSplittingRuleFactory.cpp
core/src/splitting/factory/RegressionSplittingRuleFactory.h
core/test/forest/CustomForestTest.cpp
core/test/forest/ForestCharacterizationTest.cpp
core/test/forest/RegressionForestTest.cpp
r-package/gradient.forest/R/RcppExports.R
r-package/gradient.forest/R/causal.forest.R
r-package/gradient.forest/R/custom.forest.R
r-package/gradient.forest/R/instrumental.forest.R
r-package/gradient.forest/R/quantile.forest.R
r-package/gradient.forest/R/regression.forest.R
r-package/gradient.forest/bindings/CustomForestBindings.cpp
r-package/gradient.forest/bindings/InstrumentalForestBindings.cpp
r-package/gradient.forest/bindings/QuantileForestBindings.cpp
r-package/gradient.forest/bindings/RegressionForestBindings.cpp
r-package/gradient.forest/tests/testthat/test_analysis_tools.R

Add a tuning parameter to discourage uneven splits.

---

r-package/grf/DESCRIPTION
r-package/grf/R/causal_forest.R
r-package/grf/R/input_validation.R
r-package/grf/R/instrumental_forest.R
r-package/grf/R/quantile_forest.R
r-package/grf/R/regression_forest.R

* Rename more R functions to use underscores instead of dots.
* Add GNU make as a system requirement.

More fixes for the CRAN submission.

---

r-package/grf/R/analysis_tools.R
r-package/grf/tests/testthat/test_causal_forest.R
r-package/grf/tests/testthat/test_print.R

Fix a bug in which split_frequencies didn't always return a matrix.

---

r-package/grf/DESCRIPTION
r-package/grf/NAMESPACE
r-package/grf/R/RcppExports.R
r-package/grf/R/causal_forest.R
r-package/grf/R/custom_forest.R
r-package/grf/R/input_utilities.R
r-package/grf/R/instrumental_forest.R
r-package/grf/R/quantile_forest.R
r-package/grf/R/regression_forest.R
r-package/grf/bindings/CustomForestBindings.cpp
r-package/grf/bindings/InstrumentalForestBindings.cpp
r-package/grf/bindings/QuantileForestBindings.cpp
r-package/grf/bindings/RcppUtilities.cpp
r-package/grf/bindings/RcppUtilities.h
r-package/grf/bindings/RegressionForestBindings.cpp
r-package/grf/tests/testthat/test_regression_forest.R

Currently only matrices of type dgCMatrix are supported.

Add R support for a sparse data representation.

---

core/src/forest/ForestTrainer.cpp
core/src/forest/ForestTrainer.h
core/src/sampling/RandomSampler.cpp
core/src/sampling/SamplingOptions.cpp
core/src/sampling/SamplingOptions.h
core/src/tree/TreeOptions.cpp
core/src/tree/TreeOptions.h
core/src/tree/TreeTrainer.cpp
core/src/tree/TreeTrainer.h
core/test/forest/ForestSmokeTest.cpp
core/test/utilities/ForestTestUtilities.cpp
r-package/grf/bindings/RcppUtilities.cpp

This functionality currently isn't exposed in R, and will likely take on
a different form when we eventually add it back.

Remove code related to proving weights for split variables.

---

core/src/forest/ForestOptions.cpp
core/src/forest/ForestOptions.h
core/src/forest/ForestTrainer.cpp
core/src/forest/ForestTrainer.h
core/src/forest/ForestTrainers.cpp
core/src/forest/ForestTrainers.h
core/src/tree/TreeOptions.cpp
core/src/tree/TreeOptions.h
core/src/tree/TreeTrainer.cpp
core/src/tree/TreeTrainer.h
core/test/commons/SparseDataTest.cpp
core/test/forest/CustomForestTest.cpp
core/test/forest/ForestCharacterizationTest.cpp
core/test/forest/ForestSmokeTest.cpp
core/test/forest/RegressionForestTest.cpp
core/test/utilities/ForestTestUtilities.cpp
core/test/utilities/ForestTestUtilities.h
r-package/grf/bindings/CustomForestBindings.cpp
r-package/grf/bindings/InstrumentalForestBindings.cpp
r-package/grf/bindings/QuantileForestBindings.cpp
r-package/grf/bindings/RcppUtilities.cpp
r-package/grf/bindings/RcppUtilities.h
r-package/grf/bindings/RegressionForestBindings.cpp

* Remove ForestTrainer#init, and consolidate initialization into the constructor
* Group options into a central ForestOptions object

Clean up forest option initialization.

---

core/src/forest/ForestPredictor.cpp
core/src/prediction/InstrumentalPredictionStrategy.cpp
core/src/prediction/InstrumentalPredictionStrategy.h
core/src/prediction/OptimizedPredictionStrategy.h
core/src/prediction/Prediction.cpp
core/src/prediction/Prediction.h
core/src/prediction/QuantilePredictionStrategy.cpp
core/src/prediction/RegressionPredictionStrategy.cpp
core/src/prediction/RegressionPredictionStrategy.h
core/src/prediction/collector/DefaultPredictionCollector.cpp
core/src/prediction/collector/DefaultPredictionCollector.h
core/src/prediction/collector/OptimizedPredictionCollector.cpp
core/src/prediction/collector/OptimizedPredictionCollector.h
core/src/prediction/collector/PredictionCollector.h
core/test/forest/RegressionForestTest.cpp
r-package/grf/bindings/AnalysisBindings.cpp
r-package/grf/bindings/RcppUtilities.cpp
r-package/grf/bindings/RcppUtilities.h
r-package/grf/tests/testthat/test_regression_forest.R

This is a step towards being able to cross-validate parameters using a small number of trees.

Along with OOB predictions, return an unbiased MSE estimate.

---

r-package/build_package.R
r-package/grf/DESCRIPTION
r-package/grf/R/regression_forest.R
r-package/grf/tests/testthat/test_regression_forest.R

This method uses the debiased OOB error estimates and the 'dice kriging'
package to select the optimal parameter values for a regression forest.

Add a method tune_regression_forest.

---

core/src/forest/ForestPredictors.cpp
core/src/forest/ForestPredictors.h
core/src/prediction/LocalLinearPredictionStrategy.cpp
core/src/prediction/LocalLinearPredictionStrategy.h
core/test/forest/LocalLinearForestTest.cpp
r-package/grf/R/RcppExports.R
r-package/grf/R/regression_forest.R
r-package/grf/bindings/RegressionForestBindings.cpp
r-package/grf/tests/testthat/test_regression_forest.R

Added linear correction variables feature with options for manual and automatic variable selection, and basic tests of functionality.

Incorporate local linear correction for selected variables

---

README.md
REFERENCE.md
r-package/grf/man/grf.Rd

Add the beginnings of a guide to the GRF algorithm.

---

r-package/grf/bindings/AnalysisToolsBindings.cpp
r-package/grf/tests/testthat/test_analysis_tools.R

In get_tree, make sure that the leaf samples are 1-indexed.

---

r-package/grf/R/average_partial_effect.R
r-package/grf/R/average_treatment_effect.R
r-package/grf/tests/testthat/test_average_effect.R
r-package/grf/tests/testthat/test_causal_forest.R

Allow subsetting in average treatment effects.

---

README.md
REFERENCE.md

Thanks @swager for your input on these sections!

Complete the first version of the algorithm reference.

---

DEVELOPING.md
README.md
REFERENCE.md
r-package/grf/DESCRIPTION
r-package/grf/man/grf.Rd

Replace `swager` with `grf-labs`.

Update references to the github organization name.

---

r-package/grf/R/average_partial_effect.R
r-package/grf/tests/testthat/test_average_effect.R

Make sure average effect estimation doesn't error on data with a single feature.

---

core/src/forest/ForestPredictors.cpp
core/src/prediction/LocalLinearPredictionStrategy.cpp
core/src/prediction/LocalLinearPredictionStrategy.h
r-package/grf/R/local_linear_forest.R
r-package/grf/R/local_linear_tuning.R
r-package/grf/R/regression_forest.R
r-package/grf/tests/testthat/test_local_linear_forest.R

* Fix a bug in local linear prediction where the penalty wasn't properly calculated.
* Make sure the default ridge penalty is the same for tuning and prediction.

Fix some issues in local linear tuning.

---

core/src/prediction/InstrumentalPredictionStrategy.cpp
core/test/prediction/InstrumentalPredictionStrategyTest.cpp
core/test/prediction/RegressionPredictionStrategyTest.cpp

Fix error prediction in instrumental_predict

---

r-package/grf/R/causal_forest.R
r-package/grf/R/custom_forest.R
r-package/grf/R/instrumental_forest.R
r-package/grf/R/local_linear_forest.R
r-package/grf/R/quantile_forest.R
r-package/grf/R/regression_forest.R

Document that the test matrix must have the same columns as the training matrix.

---

r-package/grf/R/input_utilities.R

Fixes bug (present since #329), whereby all forests without explicit clusters were broken.

Fix validate_clusters.

---

r-package/grf/R/causal_forest.R
r-package/grf/R/causal_tuning.R
r-package/grf/R/input_utilities.R
r-package/grf/tests/testthat/test_causal_forest_tuning.R

Addresses API inconsistency discussed in #349

 Update API for causal forest tuning to make role of orthogonalization explicit.

---

core/src/prediction/collector/SampleWeightComputer.cpp

remove unused counter: num_leaves

---

README.md

* Remove the authors section.
* Update the GRF paper reference now that it's published.
* Fix an outdated link to the travis build.
* Add a note around issues labelled 'question'.

Small updates to README.

---

r-package/grf/R/boosted_regression_forest.R
r-package/grf/R/causal_forest.R
r-package/grf/R/causal_tuning.R
r-package/grf/R/custom_forest.R
r-package/grf/R/instrumental_forest.R
r-package/grf/R/local_linear_forest.R
r-package/grf/R/quantile_forest.R
r-package/grf/R/regression_forest.R
r-package/grf/R/regression_tuning.R

Clarify docstring for honesty, honesty.fraction, prune.empty.leaves

---

r-package/grf/R/average_late.R
r-package/grf/R/input_utilities.R
r-package/grf/tests/testthat/test_average_effect.R

Replace some accidental 4 space indents with 2 spaces.

R code: fix stray indentation

---

REFERENCE.md
core/src/forest/ForestOptions.cpp
core/src/forest/ForestOptions.h
core/src/tree/Tree.cpp
core/src/tree/Tree.h
core/src/tree/TreeOptions.cpp
core/src/tree/TreeOptions.h
core/src/tree/TreeTrainer.cpp
core/src/tree/TreeTrainer.h
core/test/tree/TreePruningUnitTest.cpp
r-package/grf/R/RcppExports.R
r-package/grf/R/boosted_regression_forest.R
r-package/grf/R/causal_forest.R
r-package/grf/R/causal_tuning.R
r-package/grf/R/custom_forest.R
r-package/grf/R/input_utilities.R
r-package/grf/R/instrumental_forest.R
r-package/grf/R/local_linear_forest.R
r-package/grf/R/quantile_forest.R
r-package/grf/R/regression_forest.R
r-package/grf/R/regression_tuning.R
r-package/grf/R/tuning_utilities.R
r-package/grf/bindings/CausalForestBindings.cpp
r-package/grf/bindings/CustomForestBindings.cpp
r-package/grf/bindings/InstrumentalForestBindings.cpp
r-package/grf/bindings/QuantileForestBindings.cpp
r-package/grf/bindings/RegressionForestBindings.cpp
r-package/grf/src/RcppExports.cpp
r-package/grf/tests/testthat/test_causal_forest.R
r-package/grf/tests/testthat/test_regression_forest.R

Towards harmonizing the tuning interface: done in separate PR for manageable diff.

Rename prune.empty.leaves -> honesty.prune.leaves

---

r-package/grf/R/input_utilities.R

* Update `validate_X` to handle a data.frame
* Add new categorical variable vignette link to the informative error message
* `&&` and `||` for consistency with the rest of grf

Input utilities: update validate_X

---

REFERENCE.md
r-package/grf/R/instrumental_forest.R

Mark instrumental forest tuning as 'experimental'.

---

experiments/benchmarking/dgps.R

Fixes:
* aw1 is swapped with aw3 (equation 27 of https://arxiv.org/pdf/1510.04342.pdf)
* aw2 remains (equation 28 of https://arxiv.org/pdf/1510.04342.pdf)
* aw3 combines aw1 and aw2 (section 6.2 of https://arxiv.org/pdf/1610.01271.pdf)
Closes #622

Corrections to the aw1-aw3 benchmarking DGPs

---

r-package/grf/tests/benchmarks/causal_benchmark.R

Add training/prediction timings of
* survival_forest
* quantile_forest
* ll_regression_forest
to `causal_benchmark.R`.

Add survival/quantile/local linear timings to benchmark script

---

r-package/grf/pkgdown/_pkgdown.yml
r-package/grf/vignettes/muhats.Rmd

This PR adds a short tutorial with a code snippet explaining how to calculate estimates of mu(x, 0) and mu(x, 1) for a causal forest. This may serve as a practical reference for questions such as #699. Does it look OK to you, @swager ?

Add a short tutorial on how to estimate mu(x, w) for a causal forest

---

r-package/grf/man/leaf_stats.causal_forest.Rd
r-package/grf/man/leaf_stats.default.Rd
r-package/grf/man/leaf_stats.instrumental_forest.Rd
r-package/grf/man/leaf_stats.regression_forest.Rd
r-package/grf/man/tune_forest.Rd

After #696 generated files are being committed. The source files for the 5 items here has subsequently been updated, but we forgot to commit the new generated output.

Update out of date .Rd files

---

r-package/grf/R/instrumental_forest.R
r-package/grf/man/instrumental_forest.Rd
r-package/grf/man/predict.instrumental_forest.Rd

A simple copy and paste from the example in the `tune_instrumental_forest` docstring - a suggestion for closing #108.

Add a simple roxygen example for `instrumental_forest`

---

r-package/grf/R/dgps.R
r-package/grf/man/generate_survival_data.Rd

Change the "type2" DGP to have uniform censoring (and center with -0.5 instead of -0.4).
Add a new dgp "type5" that is the same as the original "type2".

Update survival DGP

---

r-package/grf/R/causal_survival_forest.R
r-package/grf/man/causal_survival_forest.Rd
r-package/grf/man/predict.causal_survival_forest.Rd

Just a minor missed renaming from #761.

Use `Y.max` instead of `tau` in causal survival docstring example

---

r-package/grf/R/causal_survival_forest.R
r-package/grf/man/causal_survival_forest.Rd

See #763 - this is towards the first bullet point.
Do you think this is a helpful doc detail @scottfleming?

Update causal_survival_forest docstring with computational details

---

r-package/grf/R/multi_regression_forest.R
r-package/grf/man/multi_regression_forest.Rd
r-package/grf/man/predict.multi_regression_forest.Rd
r-package/grf/tests/testthat/test_plot.R

Only two minor things to address: use `FALSE` instead of `F` in a docstring and only run plotting tests if DiagrammeR is installed.

Make R CMD check happy

---

r-package/grf/tests/testthat/test_regression_forest.R

Remove old defunct test

---

r-package/grf/R/multi_arm_causal_forest.R
r-package/grf/man/multi_arm_causal_forest.Rd

Just heeding @jtibshirani's suggestion and tacking on an "experimental" tag for the first release.

Add "experimental" tag to multi arm causal forest

---

core/src/relabeling/MultiCausalRelabelingStrategy.cpp

This PR only rewrites a few expressions in an algebraically equivalent way. This commit only splits the expression
`Eigen::ArrayXXd rho = (W_centered * A_p_inv.transpose()).array().colwise() * (Y_centered - W_centered * beta).array()`
into two, which will make adding more than one outcome easier in a follow up PR.

Reorder multi arm causal forest relabeling strategy slightly

---

README.md
r-package/grf/R/grf-package.R
r-package/grf/man/grf-package.Rd

Closes #791 (thanks @dlindelof)

Remove old out-of-sync sentence in doc example

---

r-package/grf/tests/benchmarks/causal_benchmark.R

Add causal survival forest check to `causal_benchmark.R`

---

core/src/relabeling/RelabelingStrategy.h

Just addressing some technical debts in the internals...

Clarify `responses_by_sample` C++ docstring

---

DEVELOPING.md

Just adding an overview of all current forests and their underlying C++ components.

Add an overview table of forests to DEVELOPING

---

r-package/grf/vignettes/README.md

Just a maintenance simplification for future contributors.

Add a README to vignettes/

---

r-package/grf/R/causal_survival_forest.R
r-package/grf/man/compute_eta.Rd

Related to #878 but want in separate commit.

Move Y.relabeled definition to compute_eta

---

r-package/grf/R/multi_arm_causal_forest.R
r-package/grf/man/multi_arm_causal_forest.Rd
r-package/grf/man/predict.multi_arm_causal_forest.Rd

Use nlevels(W) in multi_arm_causal_forest

---

r-package/grf/tests/testthat/test_analysis_tools.R
r-package/grf/tests/testthat/test_average_effect.R
r-package/grf/tests/testthat/test_boosted_regression_forest.R
r-package/grf/tests/testthat/test_causal_forest_tuning.R
r-package/grf/tests/testthat/test_causal_survival_forest.R
r-package/grf/tests/testthat/test_multi_regression_forest.R
r-package/grf/tests/testthat/test_probability_forest.R
r-package/grf/tests/testthat/test_survival_forest.R

Follow-up to #722 with some more replacements.

Use expect_equal/expect_lt/expect_gt in tests

---

core/src/prediction/ProbabilityPredictionStrategy.cpp
core/src/prediction/ProbabilityPredictionStrategy.h
r-package/grf/tests/testthat/test_probability_forest.R

Updates sample weighted prediction for `probability_forest` in accordance with #796.

Update sample weights for probability forest

---

r-package/grf/tests/testthat/test_causal_forest.R
r-package/grf/tests/testthat/test_causal_forest_tuning.R
r-package/grf/tests/testthat/test_causal_survival_forest.R
r-package/grf/tests/testthat/test_clustered_standard_errors.R
r-package/grf/tests/testthat/test_confidence_intervals.R
r-package/grf/tests/testthat/test_error_estimation.R
r-package/grf/tests/testthat/test_instrumental_forest.R
r-package/grf/tests/testthat/test_instrumental_forest_tuning.R
r-package/grf/tests/testthat/test_ll_regression_forest.R
r-package/grf/tests/testthat/test_multi_arm_causal_forest.R
r-package/grf/tests/testthat/test_probability_forest.R
r-package/grf/tests/testthat/test_quantile_forest.R
r-package/grf/tests/testthat/test_regression_forest.R
r-package/grf/tests/testthat/test_regression_forest_tuning.R

Second follow-up to #722 with some more replacements.

Use expect_lt/expect_gt in tests

---

REFERENCE.md

Just adding @jtibshirani's cropped logo from the README here too.

Add logo to REFERENCE

---

core/src/commons/Data.cpp

Simplify set_outcome/set_treatment

---

core/src/commons/utility.cpp
core/src/commons/utility.h
core/src/forest/ForestTrainer.cpp
core/src/prediction/InstrumentalPredictionStrategy.cpp
core/src/prediction/LLCausalPredictionStrategy.cpp
core/src/prediction/LocalLinearPredictionStrategy.cpp
core/src/prediction/PredictionValues.h
core/src/prediction/QuantilePredictionStrategy.cpp
core/src/prediction/RegressionPredictionStrategy.cpp
core/src/tree/TreeOptions.h
core/test/commons/utilitytest.cpp
core/test/prediction/InstrumentalPredictionStrategyTest.cpp
core/test/prediction/QuantilePredictionStrategyTest.cpp
core/test/prediction/RegressionPredictionStrategyTest.cpp
core/test/relabeling/InstrumentalRelabelingStrategyTest.cpp
core/test/relabeling/QuantileRelabelingStrategyTest.cpp
core/test/sampling/RandomSamplerTest.cpp
r-package/grf/bindings/AnalysisToolsBindings.cpp
r-package/grf/bindings/CausalForestBindings.cpp
r-package/grf/bindings/InstrumentalForestBindings.cpp
r-package/grf/bindings/QuantileForestBindings.cpp
r-package/grf/bindings/RcppUtilities.cpp
r-package/grf/bindings/RegressionForestBindings.cpp

Remove some unused #include's

---

r-package/grf/bindings/AnalysisToolsBindings.cpp
r-package/grf/bindings/CausalForestBindings.cpp
r-package/grf/bindings/CausalSurvivalForestBindings.cpp
r-package/grf/bindings/InstrumentalForestBindings.cpp
r-package/grf/bindings/MultiCausalForestBindings.cpp
r-package/grf/bindings/MultiRegressionForestBindings.cpp
r-package/grf/bindings/ProbabilityForestBindings.cpp
r-package/grf/bindings/QuantileForestBindings.cpp
r-package/grf/bindings/RegressionForestBindings.cpp
r-package/grf/bindings/SurvivalForestBindings.cpp
r-package/grf/src/RcppExports.cpp

Pass forest_object as const reference

---

core/src/prediction/ProbabilityPredictionStrategy.cpp

Update the sample weighted variance in ProbabilityPredictionStrategy with the correct adjustment by @swager in #774.

Update sample weighted variance for probability_forest

---

r-package/grf/R/multi_arm_causal_forest.R
r-package/grf/man/multi_arm_causal_forest.Rd
r-package/grf/man/predict.multi_arm_causal_forest.Rd

Allows the example to work in case the treatment is binary

Use drop=FALSE in example

---

core/test/prediction/MultiCausalPredictionStrategyTest.cpp

Minor test update

---

r-package/grf/DESCRIPTION
r-package/grf/man/grf-package.Rd

Bumping @erikcs up to 'author' since he's contributed a lot of core
functionality (missing data handling, survival forests, multi-causal forests...)

List Erik Sverdup as author of package

---

core/src/prediction/MultiCausalPredictionStrategy.cpp
core/test/prediction/MultiCausalPredictionStrategyTest.cpp
r-package/grf/tests/testthat/test_causal_forest.R
r-package/grf/tests/testthat/test_multi_arm_causal_forest.R

Adding the final item of #796.

Add sample weighted variance to MultiCausalPredictionStrategy

---

azure-pipelines.yml
core/test/prediction/MultiCausalPredictionStrategyTest.cpp

Compile clang/gcc build with Eigen's runtime assertions.

Add Eigen debug flag to Azure gcc/clang build

---

core/src/prediction/CausalSurvivalPredictionStrategy.cpp
core/src/prediction/CausalSurvivalPredictionStrategy.h
core/src/prediction/InstrumentalPredictionStrategy.cpp
core/src/prediction/InstrumentalPredictionStrategy.h

Thanks to @crflynn for pointing this out. Closes #1004

Make NUM_TYPES a member variable

---

r-package/grf/tests/testthat/test_survival_forest.R

Add a convenient ~approx invariance test that on complete data survival and regression forests are very similar.

Add a survival forest test

---

r-package/grf/R/tune_forest.R

Continue tuning procedure even if some draws are inadmissible. Closes #1066.

Allow some inadmissible draws in tuning

---

r-package/grf/R/causal_forest.R
r-package/grf/R/causal_survival_forest.R
r-package/grf/R/get_scores.R
r-package/grf/R/instrumental_forest.R
r-package/grf/R/ll_regression_forest.R
r-package/grf/R/multi_arm_causal_forest.R
r-package/grf/R/multi_regression_forest.R
r-package/grf/R/probability_forest.R
r-package/grf/R/quantile_forest.R
r-package/grf/R/regression_forest.R
r-package/grf/R/survival_forest.R

Use parent forest seed in auxiliary forest

---

r-package/grf/R/causal_survival_forest.R

#1055 accidentally dropped did when rewriting. Will most likely have inconsequential effects, but tagging @scottfleming and @CrystalXuR who's using the development version of CSF.

Add left out W.forest tune argument in CSF

---

r-package/grf/R/causal_survival_forest.R
r-package/grf/man/causal_survival_forest.Rd

Adding some clarification on paper vs implementation @yifan-cui

Add survival function geq note to CSF

---

REFERENCE.md

Adding a note on this for completeness sake (@shanjukta-nath had an application with many arms where MGRF would most likely not be the best choice out-of-the box)

Add scaling note on MGRF to REFERENCE

---

releases/CHANGELOG.md

The most recent CHANGELOG entries are in order Changed/Added/Fixed. Update 2.1.0 to follow same.

Update CHANGELOG order

---

r-package/grf/vignettes/survival.Rmd

Add some grammar fixes after running through google docs (imitating @scottfleming's razor sharp grammar skills)

Fix some grammar in vignette

---

r-package/grf/vignettes/rate.Rmd
r-package/grf/vignettes/survival.Rmd

Adding some clarifications pointed out by @yifan-cui

Add vignette clarification

---

REFERENCE.md

Clarifying the Q&A to emphasize that with appropriately tweaked tuning parameters, GRF can scale to very large data sets.

Update large data note in REFERENCE

---

r-package/grf/vignettes/survival.Rmd

adding paper with @CrystalXuR and @nignatiadis

Add metalearner reference to survival vignette

---

README.md
r-package/grf/R/grf-package.R
r-package/grf/man/grf-package.Rd
r-package/grf/vignettes/grf.Rmd

Replace test_calibration with the new and more interpretable RATE/TOC.

Add RATE to usage example

---

r-package/grf/R/dgps.R

Thanks to @bokelmab for pointing out.
(closes #1239).

Fix "ai1" and "ai2" example DGPs

---

r-package/grf/R/average_treatment_effect.R
r-package/grf/R/get_scores.R
r-package/grf/R/rank_average_treatment.R

!=0 --> >0

---

r-package/grf/R/causal_survival_forest.R

This change has no effect on statistical output, it only simplifies the internal workaround used to compute OOB predictions on a modified training sample. The original forest can be trained with compute.oob.predictions = TRUE since these are needed to form S(t, x, w), and this final predict call now needs one less roundtrip to serialize the forest.

Simplify CSF oob workaround

---

r-package/grf/R/lm_forest.R
r-package/grf/man/predict.lm_forest.Rd

Add optional drop argument to predict.lm_forest

---

r-package/grf/vignettes/maq.Rmd

Reverting as the plot looks OK, the vignette just didn't show the latest rendering.

Revert "Update plot in maq vignette"

---

r-package/grf/R/instrumental_forest.R
r-package/grf/man/instrumental_forest.Rd

Make the docstring a bit less sparse.
closes #1348

Add ATE ex. to iv forest docstring

---

r-package/grf/R/get_scores.R

Closes #1343 (thanks to @howardzzhang for pointing out)

Fix weak instrument warning

---

azure-pipelines.yml

Install vignette requirement via cran

---

r-package/grf/R/instrumental_forest.R
r-package/grf/man/predict.instrumental_forest.Rd

(accidentally omitted in #1349)

Consistent instrumental_forest.predict docstring

---

r-package/grf/R/rank_average_treatment.R

Add overlap warning to RATE

---

r-package/grf/R/plot.R

Make the default axis title more informative.

Change TOC axis label to "Treated fraction (q)"

---

r-package/grf/R/rank_average_treatment.R
r-package/grf/man/rank_average_treatment_effect.Rd

Fix X2 -> X1 in RATE docstring example

---

r-package/grf/R/rank_average_treatment.R

Check not necessary after #1412

Remove redundant condition

---

core/src/analysis/SplitFrequencyComputer.cpp
core/src/analysis/SplitFrequencyComputer.h
core/src/commons/Data.cpp
core/src/prediction/collector/SampleWeightComputer.cpp
core/src/prediction/collector/SampleWeightComputer.h
core/src/prediction/collector/TreeTraverser.cpp
core/src/prediction/collector/TreeTraverser.h
core/src/splitting/CausalSurvivalSplittingRule.h
core/src/splitting/InstrumentalSplittingRule.h
core/test/analysis/SplitFrequencyUnitTest.cpp
core/test/forest/ForestSmokeTest.cpp
core/test/splitting/MultiCausalSplittingRuleTest.cpp
core/test/splitting/MultiRegressionSplittingRuleTest.cpp
core/test/splitting/SplittingRuleInvarianceTest.cpp
core/test/splitting/SurvivalSplittingRuleTest.cpp
core/test/tree/TreePruningUnitTest.cpp
r-package/grf/bindings/AnalysisToolsBindings.cpp

Update some files overlooked in #1424 (these preambles have some hyphens and were missed by find+replace).

Add copyright notice to remaining source files

---

r-package/grf/R/causal_forest.R
r-package/grf/R/causal_survival_forest.R
r-package/grf/R/get_scores.R
r-package/grf/R/instrumental_forest.R
r-package/grf/R/ll_regression_forest.R
r-package/grf/R/multi_arm_causal_forest.R
r-package/grf/R/multi_regression_forest.R
r-package/grf/R/probability_forest.R
r-package/grf/R/quantile_forest.R
r-package/grf/R/regression_forest.R
r-package/grf/R/survival_forest.R

Use parent forest num.threads in auxiliary forest 

---

r-package/grf/vignettes/maq.Rmd

Some shortening and simplifications.

Update maq vignette

---

core/src/splitting/SurvivalSplittingRule.cpp
core/src/splitting/SurvivalSplittingRule.h
core/src/splitting/factory/CausalSurvivalSplittingRuleFactory.cpp
core/src/splitting/factory/CausalSurvivalSplittingRuleFactory.h
core/src/splitting/factory/InstrumentalSplittingRuleFactory.cpp
core/src/splitting/factory/InstrumentalSplittingRuleFactory.h
core/src/splitting/factory/MultiCausalSplittingRuleFactory.cpp
core/src/splitting/factory/MultiCausalSplittingRuleFactory.h
core/src/splitting/factory/MultiRegressionSplittingRuleFactory.cpp
core/src/splitting/factory/MultiRegressionSplittingRuleFactory.h
core/src/splitting/factory/ProbabilitySplittingRuleFactory.cpp
core/src/splitting/factory/ProbabilitySplittingRuleFactory.h
core/src/splitting/factory/RegressionSplittingRuleFactory.cpp
core/src/splitting/factory/RegressionSplittingRuleFactory.h
core/src/splitting/factory/SplittingRuleFactory.h
core/src/splitting/factory/SurvivalSplittingRuleFactory.cpp
core/src/splitting/factory/SurvivalSplittingRuleFactory.h
core/src/tree/TreeTrainer.cpp
core/test/splitting/SplittingRuleInvarianceTest.cpp
core/test/splitting/SurvivalSplittingRuleTest.cpp

Initialize relabeled_failures in SurvivalSplittingRule ctor
