r-package/build_package.R, r-package/gradient.forest/configure
This should allow for installation through `dev_tools::install_github`.
=> Move the source copying logic to a  file.

core/src/forest/ForestPredictor.cpp, core/src/forest/ForestPredictor.h, core/src/prediction/CustomPredictionStrategy.cpp, core/src/prediction/CustomPredictionStrategy.h, core/src/prediction/DefaultPredictionStrategy.h, core/src/prediction/InstrumentalPredictionStrategy.cpp, core/src/prediction/InstrumentalPredictionStrategy.h, core/src/prediction/OptimizedPredictionStrategy.h, core/src/prediction/PredictionValues.cpp, core/src/prediction/PredictionValues.h, core/src/prediction/QuantilePredictionStrategy.cpp, core/src/prediction/QuantilePredictionStrategy.h, core/src/prediction/RegressionPredictionStrategy.cpp, core/src/prediction/RegressionPredictionStrategy.h, core/src/prediction/collector/DefaultPredictionCollector.cpp, core/src/prediction/collector/DefaultPredictionCollector.h, core/src/prediction/collector/OptimizedPredictionCollector.cpp, core/src/prediction/collector/OptimizedPredictionCollector.h, core/src/prediction/collector/PredictionCollector.h, core/src/serialization/PredictionValuesSerializer.cpp, core/test/prediction/QuantilePredictionStrategyTest.cpp, core/test/serialization/SerializationTest.cpp
* Pull the creation of the in-bag trees matrix into ForestPredictor.
* Restructure optimized prediction to match the default strategy.
* Collect leaf prediction values during optimized prediction.
* Use precomputed values in instrumental variance calculation.
=> Allow variance computations to use precomputed values.

r-package/gradient.forest/tests/testthat/test_average_effect.R
This is a stopgap until we can get a better handle on default tuning parameters.
=> Fix the failing ATE tests by updating the seed.

r-package/grf/R/analysis.tools.R, r-package/grf/R/print.R, r-package/grf/bindings/AnalysisBindings.cpp, r-package/grf/tests/testthat/test_analysis_tools.R
```
> tree
GRF tree object 
Number of training samples:  316 
Variable splits: 
(1) split_variable: X.36  split_value: 0.749412 
(2) split_variable: X.27  split_value: 0.166218 
(4) split_variable: X.24  split_value: -0.313746 
(8) split_variable: X.32  split_value: 0.0598619 
(12) split_variable: X.7  split_value: 0.200829 
(20) split_variable: X.2  split_value: -0.0682765 
(30) * num_samples: 3 
(31) * num_samples: 4 
(21) * num_samples: 6 
(13) split_variable: X.33  split_value: 0.101998 
(22) * num_samples: 3 
(23) * num_samples: 6 
...
```
=> Implement pretty printing for trees.

r-package/grf/R/causal.forest.R, r-package/grf/R/custom.forest.R, r-package/grf/R/instrumental.forest.R, r-package/grf/R/quantile.forest.R, r-package/grf/R/regression.forest.R
* Decrease alpha to 0.01.
* Remove the option to specify ci.group.size if the forest does not support confidence intervals.
=> Fixes to R default parameters.

r-package/grf/bindings/Makevars
These only make sense in a local context, and are not used when building the R package.
=> In Makevars, remove unused settings for CC and CCX.

r-package/grf/R/instrumental_forest.R, r-package/grf/R/quantile_forest.R, r-package/grf/R/regression_forest.R
The old default of 2/3 * p was still being used in places, which was causing poor performance with even moderately large p.
=> Ensure we always default mtry to sqrt(p) + 20.

core/src/forest/ForestOptions.cpp, core/src/forest/ForestOptions.h, core/src/forest/ForestPredictor.cpp, core/src/forest/ForestPredictor.h, core/src/tree/TreeOptions.cpp, core/src/tuning/ParameterTuner.cpp, core/src/tuning/ParameterTuner.h, core/test/tuning/ParameterTunerTest.cpp, r-package/grf/R/RcppExports.R, r-package/grf/R/regression_forest.R, r-package/grf/bindings/RegressionForestBindings.cpp
Currently, the procedure just selects min node size through simple cross-validation.
We expect to make continual performance improvements to this tuning strategy.
=> Add a tune.parameters option to regression_train.

r-package/grf/R/input_utilities.R
Previously this default was specified in C++, but after the options code
was restructured, we're now providing the it in R.
Note that the default has also changed to 10, from 5 as it was in the C++ code.
=> Make sure to default the min node size to 10.

r-package/grf/R/average_treatment_effect.R, r-package/grf/tests/testthat/test_average_effect.R, r-package/grf/tests/testthat/test_print.R
The overlap-weighted effect is useful in situations with poor overlap (Li et al., 2017), and is defined as sum_{i = 1}^n e(Xi) (1 - e(Xi)) E[Y(1) - Y(0) | X = Xi] / sum_{i = 1}^n e(Xi) (1 - e(Xi)).
Addresses #176.
=> Add functionality for overlap-weighted treatment effect.

core/src/forest/ForestPredictor.cpp, core/src/forest/ForestPredictor.h, core/src/forest/ForestTrainer.cpp, core/src/prediction/collector/DefaultPredictionCollector.cpp, core/src/prediction/collector/DefaultPredictionCollector.h, core/src/prediction/collector/OptimizedPredictionCollector.cpp, core/src/prediction/collector/OptimizedPredictionCollector.h, core/src/prediction/collector/PredictionCollector.h, core/src/sampling/RandomSampler.cpp, core/src/sampling/RandomSampler.h, core/src/serialization/TreeSerializer.cpp, core/src/tree/Tree.cpp, core/src/tree/Tree.h, core/src/tree/TreeTrainer.cpp, core/test/sampling/RandomSamplerTest.cpp, core/test/serialization/SerializationTest.cpp, r-package/grf/bindings/AnalysisBindings.cpp
Addresses #145.
In experiments using a sample fraction of 0.10, this shows a ~40% reduction in peak memory usage.
=> For each tree, switch to storing the samples which were drawn as opposed to out-of-bag.

core/src/prediction/RegressionPredictionStrategy.cpp, core/src/prediction/collector/OptimizedPredictionCollector.cpp
* Ensure we calculate tree variance correctly.
* Make sure to return NAN when there are too few trees to perform the calculation.
=> Fix a couple issues in computing the debiased error.

core/CMakeLists.txt
R package builds enable level O2 by default, so using the same level in the pure C++ build provides consistency when testing and profiling performance.
=> Enable O2 compiler optimization for the pure C++ build.

README.md, r-package/grf/R/causal_forest.R, r-package/grf/R/instrumental_forest.R, r-package/grf/R/regression_forest.R, r-package/grf/tests/testthat/test_causal_forest.R, r-package/grf/tests/testthat/test_regression_forest.R
Most grf workflows involve computing OOB predictions on the training set. The current implementation doesn't cache these predictions, resulting in needless repeat computation. To avoid this, we now simply make OOB predictions by default during training, so that they are immediately available whenever needed.
Addresses a point discussed in #238
=> Compute OOB predictions during training

r-package/grf/R/plot.R, r-package/grf/tests/testthat/test_plot.R
Addresses part of https://github.com/grf-labs/grf/issues/298.
When the data matrix includes column names, this is how the plot now looks:
=> In tree plotting, include the name of the column when describing a variable split.

REFERENCE.md, core/src/sampling/RandomSampler.cpp, r-package/grf/R/causal_forest.R, r-package/grf/R/custom_forest.R, r-package/grf/R/input_utilities.R, r-package/grf/R/instrumental_forest.R, r-package/grf/R/local_linear_forest.R, r-package/grf/R/quantile_forest.R, r-package/grf/R/regression_forest.R, r-package/grf/tests/testthat/test_average_effect.R
If some clusters are smaller than `samples_per_cluster`, the whole cluster is used every time the cluster is drawn. Note that clusters with less than `samples_per_cluster` observations get relatively smaller weight than others in training the forest, i.e., the contribution of a given cluster to the final forest scales with the minimum of the number of observations in the cluster and `samples_per_cluster`.
=> Allow samples per cluster to be larger than smallest cluster size.

r-package/grf/R/plot.R
I had been, unfortunately, looking at outdated sample code for grf which included a use of "create_dot_body" which has been moved into a sub-method for plot.grf_tree since. As "create_dot_body" was listed in the 00index.html, I was under the assumption it should be available as a method even though it was not. Maybe this commit will help prevent confusion of that kind while still maintaining the commentary for development purposed. Would this comply with the GRF coding/documentation practices?
=> Disable roxygen comments processing for unavailable methods

r-package/grf/bindings/CustomForestBindings.cpp, r-package/grf/tests/testthat/test_custom_forest.R
The training data was used as test data in prediction with a custom forest
=> Fix train/test data assignment in custom_forest

r-package/grf/R/RcppExports.R, r-package/grf/R/quantile_forest.R, r-package/grf/bindings/QuantileForestBindings.cpp, r-package/grf/tests/testthat/test_quantile_forest.R
Fixes two issues with quantile forest introduced with the Data/Observations rewrite in commit 996f3b3fd4d89761b7b9ed6b0da31dbbba6895ac.
1. Nondeterministic junk output from predict caused by
a. bindings failing to subtract 1 from outcome_index to go from R to C indexing conventions
b. R code passing [X, null] = X rather than [X, Y] to the C code 
2. predict(forest) giving an error, caused by disagreement between R and C code on argument order.
Closes #387.
=> Fix quantile forest bindings

core/src/prediction/Prediction.h, r-package/grf/bindings/RcppUtilities.cpp
This commit removes references to `Prediction#contains_excess_error_estimates`,
which were accidentally committed in #327 even though the method was refactored
away.
=> Fix the package build.

r-package/grf/tests/testthat/test_forest_summaries.R
This was accidentally broken in #327 because we don't run the R tests as part
of the build.
=> Fix a failing test case in test_forest_summaries.

r-package/grf/DESCRIPTION, r-package/grf/R/plot.R
The DiagrammeR package is quite large and can be expensive to install from
source. Since it is only used when plotting trees, it can be demoted to
'Suggests' as opposed to 'Imports'.
=> Make DiagrammeR a suggested dependency.

r-package/grf/R/RcppExports.R, r-package/grf/R/causal_forest.R, r-package/grf/R/causal_tuning.R, r-package/grf/R/custom_forest.R, r-package/grf/R/instrumental_forest.R, r-package/grf/R/local_linear_forest.R, r-package/grf/R/quantile_forest.R, r-package/grf/R/regression_forest.R, r-package/grf/R/regression_tuning.R, r-package/grf/bindings/AnalysisToolsBindings.cpp, r-package/grf/bindings/CustomForestBindings.cpp, r-package/grf/bindings/InstrumentalForestBindings.cpp, r-package/grf/bindings/QuantileForestBindings.cpp, r-package/grf/bindings/RcppUtilities.cpp, r-package/grf/bindings/RcppUtilities.h, r-package/grf/bindings/RegressionForestBindings.cpp
For regression, causal, and instrumental forests, we allow precompute OOB
predictions during training by default. This PR pushes that computation into
the C++ bindings to avoid an extra round-trip between R and C++. With this
change in place, many common workflows (such as training a forest, then running
`average_treatment_effect`) should not require any deserialization of the
forest at all.
It also makes the following two refactors related to `compute.oob.predictions`:
- Make sure custom forests accept the `compute.oob.predictions` parameter.
- Group all training parameters together that are related to computation.
=> Avoid extra round-trip when precomputing OOB predictions.

experiments/acic18/script.R, r-package/grf/R/causal_forest.R, r-package/grf/R/causal_tuning.R, r-package/grf/R/custom_forest.R, r-package/grf/R/input_utilities.R, r-package/grf/R/instrumental_forest.R, r-package/grf/R/local_linear_forest.R, r-package/grf/R/quantile_forest.R, r-package/grf/R/regression_forest.R, r-package/grf/R/regression_tuning.R, r-package/grf/tests/testthat/test_average_effect.R, r-package/grf/tests/testthat/test_clustered_standard_errors.R
In our R code, method parameters always contain dots instead of underscores.
=> Fix the naming style of samples.per.cluster.

r-package/grf/R/RcppExports.R, r-package/grf/R/causal_forest.R, r-package/grf/R/causal_tuning.R, r-package/grf/R/local_linear_forest.R, r-package/grf/bindings/CausalForestBindings.cpp
* Add a binding for `causal_train`, so that the  R `causal_forest` methods consistently call into `CausalForestBindings` (and not `InstrumentalForestBindings` as well).
* Remove the `instrument_index` parameter from all methods in `CausalForestBindings`.
=> Clean-up the causal forest bindings and related logic.

r-package/grf/R/local_linear_forest.R
This parameter can never be enabled, because we don't allow OOB predictions to
be precomputed for local linear forests.
=> Remove compute.oob.predictions from ll_regression_forest.

r-package/grf/R/merge_forests.R, r-package/grf/tests/testthat/test_merge_forests.R
This fixes a bug where merged forests did not contain some attributes that are
required for calling follow-up methods such as `Y.hat` and `W.hat`.
=> Ensure merged forests contain the necessary saved attributes.

r-package/grf/NAMESPACE, r-package/grf/R/causal_forest.R, r-package/grf/R/causal_tuning.R, r-package/grf/R/print.R, r-package/grf/R/regression_forest.R, r-package/grf/R/regression_tuning.R, r-package/grf/R/tuning_utilities.R, r-package/grf/tests/testthat/test_print.R
Closes #237 
ref. meeting: display tuning output as average error over q-quantiles of parameters
```R
library(grf)
p = 4
n = 1000
X = matrix(2 * runif(n * p) - 1, n, p)
W = rbinom(n, 1, 0.5)
TAU = 0.1 * (X[,1] > 0)
Y = TAU * (W  - 1/2) + 2 * rnorm(n)
tuned.forest = causal_forest(X, Y, W, num.trees = 400, tune.parameters = TRUE)
print(tuned.forest$tuning.output)
```
```
Optimal tuning parameters: 
error: 4.193
min.node.size: 34
mtry: 2
alpha: 0.07687
imbalance.penalty: 0.8897
Average error by 5-quantile:
min.node.size    error
[1,2] 4.260210
(2,5] 4.235934
(5,13] 4.212460
(13,31] 4.198461
(31,62] 4.196825
mtry    error
[1,2] 4.223719
(2,3] 4.219167
(3,4] 4.224174
alpha    error
[1.32e-05,0.053] 4.222068
(0.053,0.106] 4.220535
(0.106,0.146] 4.225789
(0.146,0.201] 4.224805
(0.201,0.25] …
```
=> Add tuning output

r-package/grf/R/causal_forest.R, r-package/grf/tests/testthat/test_average_effect.R
Closes #270, allowing the number of trees in the "local centering" step to be an increasing function of `num.trees`.
Thank you to @klosins for simulations. We'll update the issue with her simulation results, but we have found basically no detectable difference between the four functions suggested in the issue.
=> Allowing number of trees in local centering step to vary

.travis.yml
This streamlines the build process a bit by separating it into 3 Travis matrices:
1. core grf C++ test compiled with gcc
2. core grf C++ test compiled with clang
3. R package tests (extension compiled with gcc, same as the image's R version)
(the `install: true` line in # 1-2 is just a blank dummy statement to prevent the travis R image from complaining about not finding a DESCRIPTION file, which is not needed)
There is some duplication, but is it enough to warrant a separate `build_core_grf.sh` that is run from `script` in 1.-2.?
[Here](https://travis-ci.com/grf-labs/grf/builds/119096869) is an example build output
=> CI: Separate core C++ and R package tests

r-package/grf/R/average_partial_effect.R, r-package/grf/R/boosted_regression_forest.R, r-package/grf/R/causal_forest.R, r-package/grf/R/causal_tuning.R, r-package/grf/R/custom_forest.R, r-package/grf/R/instrumental_forest.R, r-package/grf/R/local_linear_causal_tuning.R, r-package/grf/R/local_linear_forest.R, r-package/grf/R/local_linear_tuning.R, r-package/grf/R/merge_forests.R, r-package/grf/R/quantile_forest.R, r-package/grf/R/regression_forest.R, r-package/grf/R/regression_tuning.R
This PR adds the default value of the parameter in all function signature descriptions (even when a default value is set in the function declaration it is convenient to not have to scroll between that and the documentation).
Also explicitly note the default values of tunable parameters (that are set internally): `min.node.size`, `sample.fraction`, `mtry`, `alpha`, `imbalance.penalty`)
=> R Docs: add default parameter value in all doc strings

REFERENCE.md
The default value for `mtry` does not reflect the [actual](https://github.com/grf-labs/grf/blob/master/r-package/grf/R/input_utilities.R#L49): max(sqrt(p + 20), p) -> min(sqrt(p) + 20, p)
=> Small update to REFERENCE

core/src/tree/TreeTrainer.cpp, core/src/tree/TreeTrainer.h
One step towards #186: split_node_internal() does not alter samples (that is done in split_node): update reference to const.
=> TreeTrainer::split_node_internal: make samples a const reference

.travis.yml
Valgrind version 3.11.0 contains the following regression:
https://bugs.launchpad.net/ubuntu/+source/valgrind/+bug/1501545
This commit updates to valgrind 3.12.0 to ensure we don't hit this bug in CI.
Because version 3.12.0 is not available for the version of Ubuntu we use, we
need to download valgrind from a personal package repository.
Thanks to @erikcs for noticing and debugging this issue.
=> Upgrade to a newer valgrind in CI to avoid a bug.

r-package/grf/tests/testthat/test_causal_forest.R
This test checks that inverse-probability of censoring weighting improves complete data MSE. Across 100 replications, the median improvement in MSE was a factor 0.75; in 97/100 tests, the improvement was better than a factor 0.9.
Addresses issue discussed in #468.
=> Solidify IPCC test.

r-package/grf/tests/testthat/test_average_effect.R, r-package/grf/tests/testthat/test_causal_forest.R, r-package/grf/tests/testthat/test_confidence_intervals.R, r-package/grf/tests/testthat/test_error_estimation.R, r-package/grf/tests/testthat/test_merge_forests.R
These tests were badly calibrated and failing too often. These modifications ensure that they pass at least 95% of the time.
(In fact, they should pass >98% of the time, with the exception of [this](https://github.com/halflearned/grf/blob/c4e0b00497787f14623a91db48620e82cfb24599/r-package/grf/tests/testthat/test_causal_forest.R#L183) test that I could not improve)
=> Improving some tests

r-package/build_package.R, r-package/grf/tests/testthat/test_causal_forest.R
Previously a lint error would halt `build_package.R`, now it continues, but prints a warning. A print() statement is added so one sees the output if sourcing the script from R.
Closes #471 
~Misc: some leftover lints in test_causal_forest.R.~ (done in _Improving some tests_ (#468))
=> CI: Only warn on lint error

r-package/grf/tests/testthat/test_regression_forest.R
The prune.empty.leaves argument was accidentally set to just prune which R pattern matches to prune.empty.leaves: change to full argument name for consistency.
=> test_regression_forest.R: fix argument name

.travis.yml, DEVELOPING.md, r-package/build_package.R
A bug in lintr hinders the CI tests on R 3.6. Disable lintr for now and revert this once https://github.com/jimhester/lintr/issues/384 has been resolved by the lintr developers.
=> CI: Disable lintr

r-package/grf/R/plot.R
In #342 we tried to exclude private helper methods from being included in the
package documentation. However we accidentally used `@keyword` instead of the
valid directive `@keywords`.
=> Fix a typo in the `@keywords` roxygen directive.

.travis.yml
Previously, the C++ characterization tests only passed when using clang because
of differences in the way random numbers were generated across platforms.
Because we build on a couple different platforms, we had to disable these tests
in CI.
Now that we've added platform-independent random number generation in #469, we
can enable the characterization tests.
=> Run the characterization tests in CI.

r-package/grf/R/analysis_tools.R, r-package/grf/R/print.R, r-package/grf/tests/testthat/test_analysis_tools.R
* Use underscores in leaf stats labels like `avg_Y`.
* Ensure we use spaces consistently.
=> Fix inconsistent formatting in print methods.

REFERENCE.md
* Explain the new parameters `honesty.fraction` and `prune.empty.leaves`.
* Update the suggested mitigation strategy when training honest forests on a
small sample.
* Clarify the parameter tuning behavior related to honesty.
Relates to #273.
=> Update honesty-related information in the algorithm reference.

README.md
The Github link accidentally only linked to open issues, change to show all open/closed questions.
=> Update questions link in README.md

core/src/forest/Forest.cpp, core/src/forest/Forest.h, core/src/forest/ForestPredictor.cpp, core/src/forest/ForestPredictor.h, core/src/forest/ForestPredictors.cpp, core/src/forest/ForestTrainer.cpp, core/src/forest/ForestTrainer.h, core/src/forest/ForestTrainers.cpp, core/src/prediction/DefaultPredictionStrategy.h, core/src/prediction/LLCausalPredictionStrategy.h, core/src/prediction/OptimizedPredictionStrategy.h, core/src/prediction/collector/DefaultPredictionCollector.cpp, core/src/prediction/collector/DefaultPredictionCollector.h, core/src/prediction/collector/OptimizedPredictionCollector.cpp, core/src/prediction/collector/OptimizedPredictionCollector.h, core/src/prediction/collector/PredictionCollector.h, core/src/relabeling/RelabelingStrategy.h, core/src/splitting/factory/InstrumentalSplittingRuleFactory.cpp, core/src/splitting/factory/InstrumentalSplittingRuleFactory.h, core/src/splitting/factory/ProbabilitySplittingRuleFactory.cpp, core/src/splitting/factory/ProbabilitySplittingRuleFactory.h, core/src/splitting/factory/RegressionSplittingRuleFactory.cpp, core/src/splitting/factory/RegressionSplittingRuleFactory.h, core/src/splitting/factory/SplittingRuleFactory.h, core/src/tree/TreeTrainer.cpp, core/src/tree/TreeTrainer.h, core/test/forest/ForestSmokeTest.cpp, core/test/relabeling/InstrumentalRelabelingStrategyTest.cpp, r-package/grf/bindings/AnalysisToolsBindings.cpp
This commit replaces most uses of `shared_ptr` with `unique_ptr`, invoking
`move` when necessary to transfer ownership.
We still use `shared_ptr` to hold the list of trees -- this will be addressed in
a follow-up.
Relates to #203.
=> Remove most references to shared_ptr.

core/src/analysis/SplitFrequencyComputer.cpp, core/src/forest/Forest.cpp, core/src/forest/Forest.h, core/src/forest/ForestTrainer.cpp, core/src/forest/ForestTrainer.h, core/src/prediction/collector/DefaultPredictionCollector.cpp, core/src/prediction/collector/OptimizedPredictionCollector.cpp, core/src/prediction/collector/SampleWeightComputer.cpp, core/src/prediction/collector/TreeTraverser.cpp, core/src/prediction/collector/TreeTraverser.h, core/src/tree/TreeTrainer.cpp, core/src/tree/TreeTrainer.h, core/test/analysis/SplitFrequencyUnitTest.cpp, r-package/grf/bindings/AnalysisToolsBindings.cpp, r-package/grf/bindings/RcppUtilities.cpp
Now, tree objects are stored directly instead of always being wrapped in
`std::shared_ptr`. Ownership of trees is explicitly transferred through
`std::move`.
This design may be changed or partially reverted as part of our work on #187 
Relates to #203.
=> Stop wrapping tree objects in shared_ptr.

core/src/commons/Data.cpp, core/src/commons/utility.cpp, core/src/commons/utility.h, core/src/prediction/ObjectiveBayesDebiaser.cpp, core/src/relabeling/CustomRelabelingStrategy.cpp, core/src/relabeling/CustomRelabelingStrategy.h, core/src/relabeling/InstrumentalRelabelingStrategy.cpp, core/src/relabeling/InstrumentalRelabelingStrategy.h, core/src/relabeling/NoopRelabelingStrategy.cpp, core/src/relabeling/NoopRelabelingStrategy.h, core/src/relabeling/QuantileRelabelingStrategy.cpp, core/src/relabeling/QuantileRelabelingStrategy.h, core/src/relabeling/RelabelingStrategy.h, core/src/sampling/RandomSampler.cpp, core/src/sampling/RandomSampler.h, core/src/sampling/SamplingOptions.cpp, core/src/sampling/SamplingOptions.h, core/src/splitting/InstrumentalSplittingRule.cpp, core/src/splitting/InstrumentalSplittingRule.h, core/src/splitting/ProbabilitySplittingRule.cpp, core/src/splitting/ProbabilitySplittingRule.h, core/src/splitting/RegressionSplittingRule.cpp, core/src/splitting/RegressionSplittingRule.h, core/src/splitting/SplittingRule.h, core/src/splitting/factory/ProbabilitySplittingRuleFactory.cpp, core/src/tree/TreeTrainer.cpp, core/src/tree/TreeTrainer.h, core/test/relabeling/InstrumentalRelabelingStrategyTest.cpp, core/test/relabeling/QuantileRelabelingStrategyTest.cpp
This PR performs some light optimizations discovered through profiling.
First, it improves memory access during the relabeling procedure:
- Use `vector` instead of `unordered_map` for relabeled responses.
- Re-use a single vector to hold relabeled responses.
It also updates the vector allocation and access strategy for code on the hot path:
- When populating vectors, use `resize` and `operator[]` instead of `reserve` and `push_back`.
- Prefer `operator[]` instead of `at` for vector element access.
For the following code snippet (that uses the recently-added `dgps.R`), this change brings the time from **133 to 113 sec**.
```
data <- gen_data(10000, 10, dgp = "simple")
num.trees <- 2000
system.time(forest.Y <- regression_forest(data$X, data$Y, num.trees = num.trees, …
```
=> Some perf improvements for training.

r-package/grf/man/grf.Rd
The documentation in `grf.Rd` is presented when running `help(grf)` from R. This commit adds some important links to the main description.
=> Add helpful links to grf.Rd.

r-package/grf/R/causal_tuning.R, r-package/grf/R/regression_tuning.R
This error was discovered when running `R CMD check` on the package in preparation for a release.
=> Fix an incorrect variable name in tuning.

r-package/grf/.Rbuildignore
Vignettes are only built on CI for online documentation, including them in the package.tar will cause R CMD check to fail:
=> Add vignettes to .Rbuildignore

core/src/analysis/SplitFrequencyComputer.cpp, core/src/forest/Forest.cpp, core/src/forest/Forest.h, core/src/forest/ForestTrainer.cpp, core/src/forest/ForestTrainer.h, core/src/prediction/CustomPredictionStrategy.cpp, core/src/prediction/CustomPredictionStrategy.h, core/src/prediction/DefaultPredictionStrategy.h, core/src/prediction/LLCausalPredictionStrategy.cpp, core/src/prediction/LLCausalPredictionStrategy.h, core/src/prediction/LocalLinearPredictionStrategy.cpp, core/src/prediction/LocalLinearPredictionStrategy.h, core/src/prediction/QuantilePredictionStrategy.cpp, core/src/prediction/QuantilePredictionStrategy.h, core/src/prediction/collector/DefaultPredictionCollector.cpp, core/src/prediction/collector/OptimizedPredictionCollector.cpp, core/src/prediction/collector/SampleWeightComputer.cpp, core/src/prediction/collector/TreeTraverser.cpp, core/src/prediction/collector/TreeTraverser.h, core/src/tree/Tree.cpp, core/src/tree/Tree.h, core/src/tree/TreeTrainer.cpp, core/src/tree/TreeTrainer.h, core/test/analysis/SplitFrequencyUnitTest.cpp, core/test/forest/ForestSmokeTest.cpp, r-package/grf/bindings/AnalysisToolsBindings.cpp, r-package/grf/bindings/RcppUtilities.cpp, r-package/grf/tests/testthat/test_cran_smoke_test.R
This fixes a regression introduced in #512 where memory usage would spike 2x
during training. Wrapping all trees with unique_ptr makes it much easier to
guarantee that their contents are not copied unintentionally.
This commit also makes sure parameters are passed by const reference in
DefaultPredictionStrategy#compute_variance, addressing another case of
unnecessary copying.
=> Use unique_ptr to hold trees.

r-package/grf/R/RcppExports.R, r-package/grf/R/analysis_tools.R, r-package/grf/bindings/AnalysisToolsBindings.cpp, r-package/grf/src/RcppExports.cpp
Addressing #187 [next to last bullet point](https://github.com/grf-labs/grf/issues/187#issuecomment-527217557): all tree information is now saved in an R forest object and `get_tree` does not have to call into C++. Simplify by removing `deserialize_tree` and do tree construction directly inside `get_tree`.
=> Remove deserialize_tree and perform tree construction in R

r-package/grf/R/analysis_tools.R, r-package/grf/R/causal_forest.R, r-package/grf/R/causal_tuning.R, r-package/grf/R/custom_forest.R, r-package/grf/R/input_utilities.R, r-package/grf/R/instrumental_forest.R, r-package/grf/R/local_linear_causal_tuning.R, r-package/grf/R/local_linear_forest.R, r-package/grf/R/local_linear_tuning.R, r-package/grf/R/quantile_forest.R, r-package/grf/R/regression_forest.R, r-package/grf/R/regression_tuning.R
Suggestion:
Instead of calling and setting the offsets afterwards
```R
data <- create_data_matrices(X, Y.centered, W.centered, sample.weights = sample.weights)
outcome.index <- ncol(X) + 1
treatment.index <- ncol(X) + 2
sample.weight.index <- ncol(X) + 3
```
do
```R
data <- create_data_matrices(X, outcome = Y.centered, treatment = W.centered, sample.weights = sample.weights)
```
All the entry names in the create_data_matrices output are exactly the same as the signature name of the bindings: train_matrix, outcome_index, etc: allowing one further down the line to make use of this simplifying idiom:
```R
data.arguments = create_data_matrices(X, outcome = Y)
arguments = c(data.arguments, "pair list of all the other arguments")
do.call(regression_train, arguments)
```
Edit: all the variable …
=> create_data_matrices: handle outcome indices

core/src/commons/Data.cpp, core/src/commons/utility.cpp, core/src/forest/Forest.cpp, core/src/forest/ForestOptions.cpp, core/src/forest/ForestPredictor.cpp, core/src/prediction/collector/DefaultPredictionCollector.cpp, core/src/prediction/collector/OptimizedPredictionCollector.cpp, core/test/forest/ForestSmokeTest.cpp
Addressing the upcoming gcc 10 which currently [fails](https://www.stats.ox.ac.uk/pub/bdr/gcc10/grf.log)
```
src/forest/ForestOptions.cpp:50:16: error: 'runtime_error' is not a member of 'std'
50 |     throw std::runtime_error("When confidence intervals are enabled, the"
|                ^~~~~~~~~~~~~
src/forest/ForestOptions.cpp: In static member function 'static grf::uint grf::ForestOptions::validate_num_threads(grf::uint)':
src/forest/ForestOptions.cpp:96:16: error: 'runtime_error' is not a member of 'std'
```
Solution: include `<stdexcept>` https://en.cppreference.com/w/cpp/error/runtime_error
=> Include <stdexcept> (gcc 10 compliance)

r-package/grf/DESCRIPTION
closes #549 
Bump minimum R version requirement from 3.3.0 (first grf release) to 3.5.0
=> Bump minimum R version to 3.5.0 (#552)

core/src/splitting/InstrumentalSplittingRule.cpp, core/src/splitting/ProbabilitySplittingRule.cpp, core/src/splitting/RegressionSplittingRule.cpp
Skip impurity calculation in large Q (pre-sorted data) for empty counts, as done in ranger.
This was already in place for [ProbabilitySplittingRule](https://github.com/grf-labs/grf/blob/master/core/src/splitting/ProbabilitySplittingRule.cpp#L216)
Closes #555
=> Add zero-check in large Q splitting rule

r-package/grf/DESCRIPTION, r-package/grf/R/average_late.R
I think originally the warnings given in average_late is incorrect. 
The `if` condition was to compare `z.hat`:
`if (min(subset.Z.hat) <= 0.01 || max(subset.Z.hat) >= 0.99)`
While the warning messages gives the range of W.hat:
`rng <- range(subset.W.hat)`
And the warning on treatment propensities: 
`Estimated treatment propensities take values between
`
However, z.hat is the instrument propensity, not the treatment propensity. I don't understand why we would compare the instrument propensity and gives warnings on treatment propensity. 
Shouldn't we change the if statement to compare `w.hat`, if we gives warnings on `w.hat`? 
I am not sure if this warning message is trying to warn `Z.hat` or `W.hat`.  So I added warning messages for both. 
Note that, I think the warnings on W.hat only …
=> Instrument forest Warning Correction

REFERENCE.md, r-package/grf/R/causal_forest.R, r-package/grf/R/tune_regression_forest.R
Minor update to section with reference to the remaining parameters to tune_forest and a note on tuning sensitivity. 
Small additional fix: update an old `tune.parameters = TRUE` reference in causal_forest and remove a superfluous statement in regression_forest.
=> REFERENCE: update tuning section 

core/src/forest/ForestTrainer.cpp, core/src/forest/ForestTrainer.h, core/src/tree/Tree.h
Removes some old unused `#includes` and drop the unnecessary if statement before ` trees.reserve`.
=> Minor ForestTrainer/Tree checkup

core/src/splitting/RegressionSplittingRule.cpp, core/src/splitting/RegressionSplittingRule.h
This regression forest implementation (ranger) balances N vs nlog n depending on where in the tree the split is sought (in large nodes, further up the tree, a linear scan over the N sorted points is quicker than sorting nL values (nL lognL), while further down the tree sorting  nS values is quicker).(more details in chapter 5 in https://arxiv.org/abs/1407.7502)
For first time readers of the code this comment might be helpful?
=> Add a comment explaining the small q / large q splitting rule

r-package/grf/bindings/AnalysisToolsBindings.cpp
Towards #577 point 1 (Rcpp bindings):
Use the Eigen suggestion on effectively filling a sparse matrix https://eigen.tuxfamily.org/dox/group__TutorialSparse.html
Did `reserve(num_neighbors)` as the obvious lower bound on the number of non-zero entries, there may be a better one? (the output weight matrix often looks more dense than sparse)
Time:
```R
n <- 2000
p <- 10
Y <- pmax(X[, 1], 0) * W + X[, 2] + pmin(X[, 3], 0) + rnorm(n)
cf <- causal_forest(X, Y, W)
system.time(w <- get_sample_weights(cf, num.threads = 1))
#master:
#this
```
This kills the Eigen insert bottleneck. Moderate time chunk as before: the slow get operator of the STL hash table.
=> compute_sample_weights: update result insertion based on Eigen docs

r-package/grf/bindings/AnalysisToolsBindings.cpp
#578 included a typdef from the Eigen documentation example. Omit this for consistency as these are not used anywhere else in the grf codebase. (Also change to emplacing the object into the vector instead of pushing it).
=> Remove typedef Eigen::Triplet

r-package/grf/R/custom_forest.R, r-package/grf/R/quantile_forest.R
These were accidentally introduced when reworking the cluster weighting API in #545.
=> Remove references to sample.weights in custom and quantile forests.

r-package/grf/R/analysis_tools.R, r-package/grf/tests/testthat/test_analysis_tools.R
#528 accidentally pushed elements onto the frontier in the wrong order.
The printed tree nodes are in the wrong order, example:
```R
set.seed(123)
n <- 20
p <- 10
Y <- abs(X[, 1]) + rnorm(n)
rf <- regression_forest(X, Y, num.trees = 1, ci.group.size = 1, honesty = F, seed = 123))
```
The tree (0-indexed):
```
> rf$`_child_nodes`
[[1]]
[[1]][[1]]
[1] 1 3 0 0 0
[[1]][[2]]
[1] 2 4 0 0 0
> rf$`_leaf_samples`
[[1]]
[[1]][[1]]
numeric(0)
[[1]][[2]]
numeric(0)
[[1]][[3]]
[1]  8 15  0  9 ## node 3 should have size 4
[[1]][[4]]
[1]  3 17  5
[[1]][[5]]
[1]  7 14 18
```
Master:
```
> get_tree(rf, 1)
GRF tree object 
Number of training samples: 10 
Variable splits: 
(1) split_variable: X.4  split_value: 0.303529 
(2) split_variable: X.8  split_value: -0.372439 
(4) * …
```
=> [Bug] Fix queue order in get_tree

r-package/grf/R/analysis_tools.R, r-package/grf/R/input_utilities.R
Earlier this all went through and produced output (which was wrong)
```R
n <- 500
p <- 10
Y <- pmax(X[, 1], 0) * W + X[, 2] + pmin(X[, 3], 0) + rnorm(n)
c.forest <- causal_forest(X, Y, W)
get_sample_weights(c.forest, matrix(0, 1, 3))
get_sample_weights(c.forest, 42) 
get_sample_weights(c.forest, c(42, 12))
```
The added input check is the same as the one performed in predict.
validate_newdata update: The change to `NCOL` from `ncol` is for case 2) and 3) above: `NCOL(c(42, 12)` is 1. `ncol(c(42,12)` is `NULL`.
=> Add validate_newdata to get_sample_weights

r-package/grf/R/tune_causal_forest.R, r-package/grf/R/tune_instrumental_forest.R, r-package/grf/R/tune_regression_forest.R, r-package/grf/R/tuning.R
Bug fix: previously we mistakingly re-computed the small forest errors instead of using the already trained OOB errors. This will change tuning output slightly as the (intended) OOB errors are used instead. This also provides a modest speedup.
=> Remove extra predict call in forest tuning

r-package/grf/tests/testthat.R, r-package/grf/tests/testthat/test_causal_forest_tuning.R, r-package/grf/tests/testthat/test_regression_forest.R, r-package/grf/tests/testthat/test_regression_forest_tuning.R
This PR enables treating warnings as errors in testthat.
One might introduce a coding error somewhere such that an existing test that passed without warning, now gives a warning (such as for example most average treatment effect functions, and tuning functions).
This PR enables warnings as errors to avoid this. It also updates tests to remove the 4 current warnings.
You can still write tests that will give a warning with `expect_error`
=> Treat warnings as errors in testthat

r-package/grf/R/average_partial_effect.R, r-package/grf/tests/testthat/test_average_effect.R
In response to #610.
In existing the implementation, we calibrated the double robustness weights used in `average_partial_effect` so that they exactly balance 3 things: W, W.hat, and an intercept. This could create numerical issues when W.hat (i.e., our out-of-bag estimate of E[W|X]) was nearly constant. Here, we do not attempt to calibrate weights to balance W.hat if there's not enough variation in W.hat (although we do still balance W and the intercept).
=> Use more stable calibration for APE in case of low variation W.hat.

r-package/grf/tests/testthat/test_regression_forest.R
Duplicate only a random subset of the data and adjust the corresponding weights.
=> Adjust sample weighting is identical to replicating samples test

README.md, r-package/grf/pkgdown/_pkgdown.yml, r-package/grf/vignettes/diagnostics.Rmd, r-package/grf/vignettes/grf.Rmd
This vignette adds two quick diagnostics checks one can do after fitting a model with grf:
* check the histogram of estimated propensity scores
* check the histogram of each Xi in the control/treated group
A note at the end of the main grf vignette refers to the collection of "Tutorials" (renamed from "Examples")
=> Add a causal forest diagnostics vignette

.travis.yml, r-package/grf/vignettes/diagnostics.Rmd
Addresses some comments in #620 
* Check balance in IPW samples
* Add a section with fit diagnostics from https://arxiv.org/abs/1902.07409
* Add the bias measure from https://arxiv.org/abs/1702.01250 
To add:
A more prominent landing page mention of the documentation vignettes: 
What would be a good place? https://grf-labs.github.io/grf shows the Tutorials on the click down menu which I thought was ok.
(to build just this vignette to see the rendered content run `pkgdown::build_article("diagnostics")`)
=> Causal forest diagnostics vignette revisions

r-package/grf/R/average_late.R, r-package/grf/R/average_partial_effect.R, r-package/grf/R/average_treatment_effect.R, r-package/grf/R/forest_summary.R, r-package/grf/tests/testthat/test_forest_summaries.R
When calculating a treatment summary statistic, if a user specifies `subset` to be equal only one of the clusters, there is an error.
```R
n <- 200
p <- 10
W <- rbinom(n, 1, 1 / (1 + exp(-X[, 2]))) + rnorm(n)
Y <- pmax(X[, 1], 0) * W + X[, 2] + pmin(X[, 3], 0) + rnorm(n)
cf <- causal_forest(X, Y, W, num.trees = 50, clusters = c(rep(1, 100), rep(2, 100)))
average_partial_effect(cf, subset = cf$clusters == 1)
Error in `contrasts<-`(`*tmp*`, value = contr.funs[1 + isOF[nn]]) : 
contrasts can be applied only to factors with 2 or more levels 
```
Add a more informative error message by checking the number of distinct observations after subsetting. Affected functions:
best_linear_projection (fixes previous mistake)
average_partial_effect
average_late …
=> More informative error message when subset equals one unit in summary functions

r-package/grf/R/average_partial_effect.R, r-package/grf/R/forest_summary.R
As mentioned in #633: add an optional parameter `debiasing.weights` to `average_partial_effect` which allows a user to bypass the forest based variance estimate Var[Wi | Xi = x]  and input custom weights (this is already present in `best_linear_projection`).
@swager as in `best_liner_prediction`, debiasing.weights is here required to be equal to length n https://github.com/grf-labs/grf/pull/615#discussion_r380324198. Is that ok?
=> Add optional debiasing.weights to average_partial_effect

core/src/splitting/factory/InstrumentalSplittingRuleFactory.cpp, core/src/splitting/factory/InstrumentalSplittingRuleFactory.h, core/src/splitting/factory/ProbabilitySplittingRuleFactory.cpp, core/src/splitting/factory/ProbabilitySplittingRuleFactory.h, core/src/splitting/factory/RegressionSplittingRuleFactory.cpp, core/src/splitting/factory/RegressionSplittingRuleFactory.h, core/src/splitting/factory/SplittingRuleFactory.h, core/src/tree/TreeTrainer.cpp, core/test/splitting/SplittingRuleInvarianceTest.cpp
A tighter upper bound for the length needed for a splitting rule's scratch array is the size of the subsample used to grow the tree, as mentioned in https://github.com/grf-labs/grf/pull/635#discussion_r395917188 by @jtibshirani .
This PR updates the SplittingRuleFactory constructor with a new length argument.
=> Set splitting rule scratch arrays to subsample size

.travis.yml
Install all R packages from source as the Travis build complains of packages being built for  R < 4.0. This can be reverted once linux binary releases are available for R 4.0
=> Travis fix for R 4.0

core/src/prediction/collector/DefaultPredictionCollector.cpp, core/src/prediction/collector/DefaultPredictionCollector.h
The [DefaultPredictionStrategy](https://github.com/grf-labs/grf/blob/master/core/src/prediction/DefaultPredictionStrategy.h) does not implement [compute_error](https://github.com/grf-labs/grf/blob/master/core/src/prediction/OptimizedPredictionStrategy.h#L104) so we can avoid [recording](https://github.com/grf-labs/grf/blob/master/core/src/prediction/collector/DefaultPredictionCollector.cpp#L98) leaf samples.
When recording leaf samples, also avoid an accidental copy (this will give a speedup for predictions with the DefaultPredictionStrategy).
Future follow up: this step may delegated to the `SampleWeightComputer`
=> Remove estimate_error from DefaultPredictionCollector

r-package/grf/R/analysis_tools.R, r-package/grf/R/average_partial_effect.R, r-package/grf/R/average_treatment_effect.R, r-package/grf/R/boosted_regression_forest.R, r-package/grf/R/causal_forest.R, r-package/grf/R/custom_forest.R, r-package/grf/R/forest_summary.R, r-package/grf/R/local_linear_forest.R, r-package/grf/R/merge_forests.R, r-package/grf/R/plot.R, r-package/grf/R/quantile_forest.R, r-package/grf/R/regression_forest.R, r-package/grf/R/survival_forest.R, r-package/grf/R/tune_causal_forest.R, r-package/grf/R/tune_instrumental_forest.R, r-package/grf/R/tune_local_linear_causal_forest.R, r-package/grf/R/tune_local_linear_forest.R, r-package/grf/R/tune_regression_forest.R
With R [release 4.0](https://stat.ethz.ch/pipermail/r-announce/2020/000653.html) `R CMD check` now automatically checks the docstring examples:
```
* R CMD check --as-cran now runs \donttest examples (which are run
by example()) instead of instructing the tester to do so.  This
can be temporarily circumvented during development by setting
environment variable _R_CHECK_DONTTEST_EXAMPLES_ to a false
value.
```
This prevents broken documentation examples from sneaking into a release.
It also has the benefit of rendering the code examples in the online documentation:
(A CRAN reviewer for policytree pointed out replacing \dontrun with \donttest)
=> Replace \dontrun with \donttest in R docstrings

r-package/grf/pkgdown/extra.js
This is an addition to #575 which corrects the online vignette links.
Example:
Under "Source:" in https://grf-labs.github.io/grf/articles/llf.html the link will now lead to the vignette source file.
=> Add pkgdown workaround for vignette urls

r-package/grf/R/RcppExports.R, r-package/grf/R/causal_forest.R, r-package/grf/R/local_linear_forest.R, r-package/grf/R/quantile_forest.R, r-package/grf/R/regression_forest.R, r-package/grf/bindings/CausalForestBindings.cpp, r-package/grf/bindings/RegressionForestBindings.cpp, r-package/grf/src/RcppExports.cpp
This is only a simplification of the way the various prediction wrappers are called. With the addition of `create_test_matrices` from #647 we can simplify all the `forest.predict` methods by using `do.call.rcpp(forest_predict_function, args)` for the bindings.
This has the added benefit of always using named arguments, avoiding errors arising from argument order switching.
Additional changes are made to make names consistent across function signatures. Code is also restructured to be consistent between functions. This was particularly relevant for local linear forests, @rinafriedberg please see if you agree. (Summary: if something is called chicken in function X, try to stick to calling it chicken every other place. If chicken comes before cow in function X, try to make chicken come …
=> Use do.call.rcpp in forest prediction functions

r-package/grf/R/causal_forest.R, r-package/grf/R/regression_forest.R
This is just a simplification follow up to #654 which included an unnecessary `modifyList`.
=> Remove an unnecessary `modifyList`

core/src/prediction/SurvivalPredictionStrategy.cpp
This is a very minor change.  If the estimate hits zero it will stay zero and we can break early. This also prevents errors from accumulating which may yield some point estimates less than zero.
```R
set.seed(123)
n <- 1000
p <- 5
failure.time <- exp(0.5 * X[, 1]) * rexp(n)
censor.time <- 2 * rexp(n)
sf <- survival_forest(X, Y, D)
min(predict(sf)$predictions)
min(predict(sf)$predictions)
```
=> Break the Kaplan-Meier loop when it hits zero

r-package/grf/R/tune_local_linear_causal_forest.R, r-package/grf/R/tune_local_linear_forest.R
A simple follow up to #654 
Also a minor fix to the docstring example in these two functions, the lambda was eaten up by `...` before.
=> Use do.call in tune_ll_regression_forest and tune_ll_causal_forest

core/src/prediction/QuantilePredictionStrategy.cpp, core/src/prediction/collector/DefaultPredictionCollector.cpp
Add a check to the DefaultPredictionCollector which is already in place for the [OptimizedPredictionCollector](https://github.com/grf-labs/grf/blob/master/core/src/prediction/collector/OptimizedPredictionCollector.cpp#L120-L124).
QuantilePredictionStrategy [segfaults](https://user-images.githubusercontent.com/7185264/81639585-367f9400-93d1-11ea-8eba-ff6e757998a7.png) if `weights_by_sample` is empty as is the case when OOB predicting with sample.fraction = 1 and honesty = TRUE as in for example [this](https://github.com/grf-labs/grf/blob/master/r-package/grf/tests/testthat/test_analysis_tools.R#L36) test case.
=> Add neighbors check to DefaultPredictionCollector

r-package/grf/R/RcppExports.R, r-package/grf/R/quantile_forest.R, r-package/grf/bindings/QuantileForestBindings.cpp, r-package/grf/src/RcppExports.cpp, r-package/grf/tests/testthat/test_quantile_forest.R
Closes #663 
~2b4c2cd + 9b123e3 is a suggested small breaking change for conformity with the rest of grf: return the point predictions in the `$predictions` attribute (and the quantiles in $quantiles). Can revert if you disagree!~
=> Add  `compute.oob.predictions` option to Quantile Forest

r-package/grf/R/quantile_forest.R
Closes #667.
```R
X = matrix(rnorm(100*10), 100, 10)
Y = rnorm(100)
qrf = quantile_forest(X, Y, quantiles=c(0.2, 0.8))
p = predict(qrf, X)
dim(p)
#[1] 100   2
```
=> Predict with training quantiles by default

r-package/grf/R/analysis_tools.R, r-package/grf/R/average_late.R, r-package/grf/R/average_partial_effect.R, r-package/grf/R/average_treatment_effect.R, r-package/grf/R/causal_forest.R, r-package/grf/R/forest_summary.R, r-package/grf/R/input_utilities.R, r-package/grf/R/instrumental_forest.R, r-package/grf/R/quantile_forest.R, r-package/grf/R/regression_forest.R, r-package/grf/R/survival_forest.R
The current grf style is to prefer `&&` over `&` as it short-circuits. This PR makes everything adhere to this where element-wise comparison is not needed with `&` or `|`.
=> Make consistent use of logical operators in R bindings

.travis.yml
Move some requirements not needed for pull request builds to the `deploy` section. This may speed up PR build times.
=> Simplify some R build options in Travis

core/src/prediction/SurvivalPredictionStrategy.cpp, core/src/prediction/SurvivalPredictionStrategy.h, r-package/grf/R/survival_forest.R, r-package/grf/tests/testthat/test_survival_forest.R
Add the optional argument `failure.times` to survival forest `predict` allowing a user to make predictions at a chosen set of failure times (addresses https://github.com/grf-labs/grf/pull/647#discussion_r417000237) 
```R
n <- 2000
p <- 5
failure.time <- exp(0.5 * X[, 1]) * rexp(n)
censor.time <- 2 * rexp(n)
s.forest <- survival_forest(X, Y, D)
s.pred <- predict(s.forest, failure.times = c(0.1, 0.5, 1))
> head(s.pred$predictions)
[,1]      [,2]      [,3]
[1,] 0.6805962 0.4427821 0.2464440
[2,] 0.4981635 0.3594178 0.3371501
[3,] 0.6571849 0.4276589 0.3011384
[4,] 0.8025943 0.6352667 0.3622079
[5,] 0.7312466 0.4533023 0.2704999
[6,] 0.6335301 0.4036986 0.2226021
```
=> Add option to predict at chosen failure times

core/test/prediction/README.md, r-package/grf/R/survival_forest.R
Survival analysis relies on `base::findInterval(Y.values, failure.values, rightmost.closed = FALSE, all.inside = FALSE, left.open = FALSE)` to relabel the event times.
These arguments are all FALSE by default, but were stated explicitly in case different R versions had different behavior.  
This PR removes declaring these redundant arguments as all R versions which grf supports (>= 3.5) does not break this.
=> Remove passing explicit default options to `findInterval()`

r-package/grf/R/survival_forest.R
* Clarify the return value in prediction.
* State that if `failure.times` are passed, they should be in increasing order.
Thanks to @davidahirshberg for pointing this out
=> Clarify the survival forest prediction documentation

core/src/forest/ForestPredictors.cpp, core/src/forest/ForestPredictors.h, core/src/prediction/SurvivalPredictionStrategy.cpp, core/src/prediction/SurvivalPredictionStrategy.h, core/test/forest/ForestCharacterizationTest.cpp, core/test/prediction/README.md, core/test/prediction/SurvivalPredictionStrategyTest.cpp, r-package/grf/R/RcppExports.R, r-package/grf/R/input_utilities.R, r-package/grf/R/survival_forest.R, r-package/grf/bindings/SurvivalForestBindings.cpp, r-package/grf/src/RcppExports.cpp, r-package/grf/tests/testthat/test_survival_forest.R
This PR adds the optional argument `prediction.type` to survival forest `predict` allowing a user to select between Kaplan-Meier (default from grf 1.2) and Nelson-Aalen for survival curve estimates.
Example
```R
n <- 500
p <- 5
failure.time <- exp(0.5 * X[, 1]) * rexp(n)
censor.time <- 2 * rexp(n)
sf <- survival_forest(X, Y, D)
predict(sf, prediction.type = "Kaplan-Meier")$predictions
predict(sf, prediction.type = "Nelson-Aalen")$predictions
```
Details:
[Nelson-Aalen](https://en.wikipedia.org/wiki/Nelson%E2%80%93Aalen_estimator) is bounded below and is needed for #660, see equation (4) in https://arxiv.org/pdf/2001.09887.pdf: the survival function of the censoring process …
=> Add optional Nelson-Aalen estimates of the survival function

r-package/grf/R/survival_forest.R
This is minor fix to #685 where we mistakingly predict with Kaplan-Meier by default, instead of the `prediction.type` the forest was trained with by default.
=> Fix the default `prediction.type` in survival predict

r-package/grf/R/forest_summary.R
See #688. This takes care of `best_linear_projection` (will make a pass over the rest of the documentation later).
=> Correct the generated documentation for `best_linear_projection`

r-package/grf/R/input_utilities.R, r-package/grf/R/survival_forest.R
This makes the `prediction.type` choices obvious from the function signature (the default `predict` behavior is to use the `prediction.type` the forest was trained with).
=> Replace `prediction.type = c("Kaplan-Meier", "Nelson-Aalen")`

core/src/prediction/SurvivalPredictionStrategy.cpp
Updating a simple check to be more idiomatic (@jtibshirani ).
=> Avoid a "control may reach end of non-void function" warning

r-package/grf/R/analysis_tools.R, r-package/grf/R/tuning.R
Explicitly declare some documented R package functions as internal. This will remove five items in the following warning message from `pkgdown` when building the online reference
```
Warning messages:
1: Topics missing from index: 
* custom_forest
* grf
* leaf_stats.causal_forest
* leaf_stats.default
* leaf_stats.instrumental_forest
* leaf_stats.regression_forest
* predict.custom_forest
* tune_forest 
```
=> Add `@keyword internal` to internal functions

experiments/acic18/script.R
The `samples.per.cluster` option was removed in grf version 1.0 and is now by default (`equalize.cluster.weights = FALSE`) set internally to the size of the largest cluster, which means that larger clusters receive larger weights than small ones.
To be closer to the original behavior, this script is updated by setting `equalize.cluster.weights` to `TRUE`, which means each school receives equal weight in ATE estimation.
(closes #693)
=> Remove `samples.per.cluster` option from the ACIC 2018 script

r-package/grf/R/RcppExports.R, r-package/grf/R/survival_forest.R, r-package/grf/bindings/SurvivalForestBindings.cpp, r-package/grf/src/RcppExports.cpp
Passing sample weights to `survival_predict` and `survival_predict_oob` is of course not needed, remove this.
=> Remove unnecessary sample weight argument from survival bindings

r-package/grf/R/input_utilities.R
`isFALSE` was introduced in [R 3.5](https://cran.r-project.org/bin/windows/base/old/3.5.0/NEWS.R-3.5.0.html) and is strictly not needed for this check.
This check is a bit convoluted because of how sample weighting was implemented with two arguments instead of one.
=> Remove an `isFALSE` in input_utilities.R

r-package/grf/R/analysis_tools.R, r-package/grf/man/split_frequencies.Rd, r-package/grf/man/variable_importance.Rd
With n equal to only 50 the docstring example variable importance is naturally not very precise
https://grf-labs.github.io/grf/reference/variable_importance.html
Increasing n to 250 looks more reasonable and does not increase build time significantly.
=> Increase n in analysis tools docstring example

r-package/grf/pkgdown/_pkgdown.yml
This is only a minor fix to the online reference: only the first word should be capitalized.
=> Fix an inconsistent capitalization in the function reference

r-package/grf/R/causal_survival_forest.R, r-package/grf/man/causal_survival_forest.Rd, r-package/grf/tests/testthat/test_causal_survival_forest.R
Instead of passing:
```
S0.hat: a list of ...
S1.hat: a list of ...
```
simplify it to:
```
E0.hat: A vector of estimates of E[Y | X, W = 1].
E1.hat: "... "
```
Note that `expected_survival` is an internal function, but for power users wishing to pass this argument the computation involved is [minor](https://github.com/grf-labs/grf/blob/master/r-package/grf/R/causal_survival_forest.R#L576).
=> Simplify two nuisance arguments in `causal_survival_forest`

r-package/grf/tests/testthat/test_analysis_tools.R
This is only a minor fix, the comparison should be pairwise (`&` not `&&`).
=> Fix a pairwise comparison in old test

r-package/build_package.R
In the R package tests we enabled treating warnings as errors in #595, but since `build_package.R` invokes the test suite differently, this option was not respected (it is respected when running R CMD check). Address this by adding a `options(warn = 2)` before `test_package` is run (currently all tests pass without warnings).
=> Treat warnings as errors in `build_package.R`

r-package/grf/R/get_scores.R
#723 accidentally omitted the `clusters` for the compliance forest. This did not cause a test error since all tests where passed with a pre-computed `compliance.score`.
=> Add missing `clusters` argument to `get_ACLATE`

.travis.yml, r-package/grf/pkgdown/_pkgdown.yml, r-package/grf/vignettes/visualize_tree.Rmd
This PR adds a short vignette entry `Visualize trees` giving a short overview of the tree plotting functionality in GRF. @susanathey mentioned the documentation could be clarified in this area, hopefully this vignette will be useful for users.
We demonstrate `plot` and `print` with `get_tree`, and emphasize these are only simple visualization tools, and refer the user to the `policytree` package (with an example) for tree-based treatment assignment rules.
A printout of the rendered vignette is attached [here](https://github.com/grf-labs/grf/files/5253388/out.pdf) for convenience.
=> Add a "Visualize trees" entry to vignettes

r-package/grf/R/causal_survival_forest.R, r-package/grf/R/tuning.R, r-package/grf/man/compute_eta.Rd, r-package/grf/man/tune_forest.Rd
This is just a two character fix to two docstrings.
=> Fix two mini typos in roxygen section

.travis.yml, core/src/relabeling/LLRegressionRelabelingStrategy.cpp
GRF contains several `Eigen` computations involving matrix products, since the dimensionality of these are determined at runtime, bugs (unlikely but not impossible) may creep in from non-conformable expressions. 
This PR sets the environment variable `PKG_CPPFLAGS="-UNDEBUG"` in the R package test which makes `Eigen` check the dimensionality of all matrix products at runtime. (This compiler flag only affects the R tests). 
From [Writing R Extensions](https://cran.r-project.org/doc/manuals/r-devel/R-exts.html): "If you wish to use assert during development. you can include -UNDEBUG in PKG_CPPFLAGS."
Check of this suggested addition:
- f1b2ac4 adds a change that should fail, but the CI passes
- 6aba480 adds the above flag to .travis.yml, causing the build to fail (as it should)
=> Set `PKG_CPPFLAGS=-UNDEBUG` in CI R test

.travis.yml
The master branch build fails because the online documentation package, pkgdown, is broken. This PR adds a workaround by installing a previous version, which appears less flaky.
=> Online docs workaround

r-package/grf/R/probability_forest.R, r-package/grf/man/predict.probability_forest.Rd, r-package/grf/man/probability_forest.Rd, r-package/grf/tests/testthat/test_probability_forest.R
This is just to ensure robustness and limit potential confusion by restricting the input class labels to be a factor. This way the class labels and ordering is unambiguous, it is given by the levels of the factor Y.
The upcoming addition in #748 will have the same restriction on the input treatment vector.
=> Require that the class labels in `probability_forest` is a factor

r-package/grf/R/causal_survival_forest.R, r-package/grf/R/dgps.R, r-package/grf/man/causal_survival_forest.Rd, r-package/grf/man/compute_eta.Rd, r-package/grf/man/generate_survival_data.Rd, r-package/grf/man/predict.causal_survival_forest.Rd, r-package/grf/tests/testthat/test_causal_survival_forest.R
The notation in the CSF paper is updated, this PR reflects that in the code.
Should take care of bullet point 2.viii. in #652
=> Rename `theta` and `tau` in causal_survival_forest

r-package/grf/R/causal_survival_forest.R, r-package/grf/man/causal_survival_forest.Rd
`causal_survival_forest(X, Y, W, D)` takes an event time `Y` but the function docstring was defined in terms of `T`: rename this to `Y`.
(the paper uses `T` for the event time but it seems better for package harmony/consistency to stick with always using `Y` as the response variable argument name, which is also the argument name for `survival_forest`)
=> Use consistent symbol for event time in causal survival forest docstring

r-package/grf/R/causal_survival_forest.R, r-package/grf/man/causal_survival_forest.Rd
`causal_survival_forest` already warns about this identifying issue, but R warnings may be easy to ignore, so here is a suggested explicit section in the docstring to document the matter:
We have not made an online vignette yet, but it is tracked in #652 and can be completed once the paper is finished. There we can provide a worked example of this + more.
Do you think this wording is OK @yifan-cui @swager?
=> Update causal_survival_forest docstring with details on follow-up time

r-package/grf/R/causal_survival_forest.R
Add a warning in `causal_survival_forest` if the supplied event data is so dense it may be a computational burden.
(closes #763).
=> Add warning if event grid is large

DEVELOPING.md, r-package/grf/DESCRIPTION
Update to the following convention (OK'd by @jtibshirani):
CRAN releases have a 3-digit version number, while the development version has 4 digits. This convention allows one to easily distinguish if a package was installed from CRAN or from GitHub (R does not allow version numbers with a "devel" tacked on).
The current CRAN version is 1.2.0
GRF installed from github will then show version number: 1.2.0.0
=> Add development version tag

r-package/grf/R/forest_summary.R, r-package/grf/man/best_linear_projection.Rd, r-package/grf/man/test_calibration.Rd
Closes #786. Thanks to @adeldaoud for reporting and @zeileis for the help with `sandwich`.
=> Add `vcov.type` to `test_calibration/best_linear_projection`

r-package/grf/R/average_treatment_effect.R, r-package/grf/man/average_treatment_effect.Rd
This paper was mentioned in the docstring description but an entry in `@references` was missing.
=> Update `@reference` section in average_treatment_effect

core/src/commons/Data.cpp, core/src/commons/Data.h, core/src/prediction/SurvivalPredictionStrategy.cpp, core/src/splitting/CausalSurvivalSplittingRule.cpp, core/src/splitting/SurvivalSplittingRule.cpp
This is just an old naming "quirk" left over in the code: we should call this `is_failure` to avoid future confusion (0: censor, 1: failure )
=> Rename `Data::is_censored` to `is_failure`

core/src/prediction/collector/DefaultPredictionCollector.cpp, core/src/prediction/collector/OptimizedPredictionCollector.cpp
In case a sample as no neighbors `nan` placeholder predictions are returned, but these have the wrong dimensions for the last entries: `mse` and `mse` which should be two scalars. This simple PR updates these two entries.
After the recent https://github.com/grf-labs/grf/commit/46107bad75fede7ac87f681f11f88360d607d3bb#diff-3d3021388b0bbfacea7179beb0f48fcc4cc0d818bf979cdb8a5dc520cb4d8b20L181 the effect of this may be sinister and segfault because of differently-sized entries.
Before that commit, it would still be "awkward": if you run 
```R
n <- 50
p <- 10
X.test <- matrix(0, 101, p)
X.test[, 1] <- seq(-2, 2, length.out = 101)
Y <- X[, 1] * rnorm(n)
qf <- quantile_forest(X, Y, quantiles = c(0.1, 0.5, 0.9), compute.oob.predictions = TRUE, num.trees = 2) …
```
=> Adjust predictions for (variance, mse, mce) in case sample has no neighbors

r-package/grf/R/causal_survival_forest.R
We do currently not compute `debiased.error` or `excess.error` so we can omit these entries.
=> Remove unused prediction output in causal survival forest

r-package/grf/R/multi_regression_forest.R, r-package/grf/man/multi_regression_forest.Rd
This is just a minor convenience for consistency with other forests like `probability_forest`.
```
> mr.forest <- multi_regression_forest(X, Y)
> head(predict(mr.forest)$predictions)
A         ABC
[1,] -0.81207945 -1.43273219
[2,] -0.04327326  0.06094848
[3,]  0.04231994  0.09658590
[4,]  0.10632419  0.18724158
[5,]  0.77469128  1.79975894
[6,] -0.56629942 -1.08416170
```
=> Add column names to multi_regression predictions

r-package/grf/R/input_utilities.R
`multi_regression_forest(X, Y)` allows:
X: matrix, data.frame, sparse matrix
Y: matrix/vector
Update `validate_observations` to be consistent and accept data.frame as well.
=> Allow data.frame in validate_observations

r-package/grf/tests/testthat/test_probability_forest.R
Update `probability_forest` tests with one more convenient invariance (same does not hold exactly for a regression_forest used for propensity estimation)
=> Add invariance test to probability_forest

r-package/grf/grf.Rproj
Depending on R version this is not always performed when running the package check from the IDE.
=> Add `-run-donttest` to Rstudio build config

r-package/grf/R/tune_local_linear_causal_forest.R, r-package/grf/R/tune_local_linear_forest.R, r-package/grf/man/tune_ll_causal_forest.Rd, r-package/grf/man/tune_ll_regression_forest.Rd
These functions are not exported anymore so running R CMD check with "-run-dontest" will cause an error since the function is not found.
=> Remove `@examples` from internal function

azure-pipelines.yml
With this flag all docstring `@examples` are run on a PR build - but it adds ~3 more minutes to the build time. Do you think it is worth having this done on every PR @jtibshirani @halflearned?
=> Do `--run-donttest` on CI

r-package/grf/R/multi_arm_causal_forest.R, r-package/grf/man/multi_arm_causal_forest.Rd
This is just a suggested paragraph on the main details behind the forest - the docstring is not a good place for a full blown description of all the details, so some parts may be a bit vague (can be laid out in full detail in a future GRF software paper / manual)
Here is the rendered output (as it will show on the website/PDF docs):
Do you think this looks reasonable @xnie, @davidahirshberg, @swager? (already went through this with @halflearned and we concurred that it was hard to explain everything in a short paragraph).
=> Add paragraph on statistical details to multi arm causal forest

r-package/grf/R/average_treatment_effect.R, r-package/grf/R/causal_survival_forest.R, r-package/grf/R/get_scores.R, r-package/grf/man/causal_survival_forest.Rd, r-package/grf/man/get_scores.causal_survival_forest.Rd, r-package/grf/man/predict.causal_survival_forest.Rd, r-package/grf/tests/testthat/test_causal_survival_forest.R
Finishes the summary function integration in #652.
=> Add causal survival forest support to `average_treatment_effect`

DEVELOPING.md, REFERENCE.md, core/src/splitting/ProbabilitySplittingRule.cpp, core/src/splitting/ProbabilitySplittingRule.h, r-package/grf/tests/testthat/test_probability_forest.R
Modify the Gini impurity measure used in splitting to count the sample_weight of sample j instead of just sample j. In the code this amounts to adjusting `class_counts` by the sample weight of each sample.
With this addition sample weighting in GRF is implemented "consistently" in the sense that the Split/Predict columns in the following table of sample weight support is either Yes/Yes or No/No for a given forest (except local linear)
| Forest                                                                  	| Relabeling                      	| Splitting 	| Predict 	| SplittingClass               	| PredictionClass                   	|
|-------------------------------------------------------------------------	|---------------------------------	|-----------	|--------- …
=> Add sample weights to ProbabilitySplittingRule

r-package/grf/R/average_treatment_effect.R, r-package/grf/tests/testthat/test_multi_arm_causal_forest.R
`matrix - vector` does not do what was intended here. Net effect was very small, added test would only fail at 1e-3 tolerance.
=> Fix broadcasting error in multi_arm_causal_forest ATE se

r-package/grf/R/average_treatment_effect.R, r-package/grf/R/forest_summary.R, r-package/grf/R/input_utilities.R
After `multi_arm_causal_forest` `Y.orig` may be a matrix and any generic code (that might end up touching a multi arm causal forest object) relying on retrieving the number of samples should do so with `NROW` for robustness. (`length` of a 2d matrix is not the number of rows).
=> Use `NROW(forest$Y.orig)` instead of `length(forest$Y.orig)`

r-package/grf/R/RcppExports.R, r-package/grf/R/causal_forest.R, r-package/grf/R/local_linear_forest.R, r-package/grf/R/regression_forest.R, r-package/grf/bindings/RegressionForestBindings.cpp, r-package/grf/man/ll_regression_forest.Rd, r-package/grf/src/RcppExports.cpp
As agreed with by @swager, disable sample.weights for local linear forests.
Currently, they are supported, but in inconsistent ways: local linear regression takes them into account during splitting but not elsewhere, same for local linear causal predictions.
Instead of implementing all this before GRF 2.0, disable this for now, pending a potential future feature.
=> Disable sample.weights for local linear forests

r-package/grf/R/dgps.R
The way all these DGPs are parameterized: needs a `e*tau` term in `m`. Missed in #734.
=> Add e*tau to NW dgps

r-package/grf/R/multi_arm_causal_forest.R, r-package/grf/man/multi_arm_causal_forest.Rd, r-package/grf/man/predict.multi_arm_causal_forest.Rd
Minor clarity improvement:
* Mention `average_treatment_effect` outcome argument in multi_arm_causal_forest docstring
* Move the detailed contrast example to end of docstring
=> Clarify `multi_arm_causal_forest` docstring

core/src/splitting/MultiRegressionSplittingRule.h, r-package/grf/tests/testthat/test_multi_regression_forest.R
The current C++ tests already lock in this behavior, but should have the same test in place in R as well to prevent an _unintentional_ change in R bindings/package to cause a regression forest to give slightly different results from a multi regression forest with one outcome.
=> Add R test that regression/multi_regression are the same

core/src/forest/ForestTrainers.cpp, core/src/forest/ForestTrainers.h, core/src/relabeling/MultiCausalRelabelingStrategy.cpp, core/src/relabeling/MultiCausalRelabelingStrategy.h, core/src/relabeling/MultiNoopRelabelingStrategy.cpp, core/src/relabeling/MultiNoopRelabelingStrategy.h, core/src/relabeling/RelabelingStrategy.h, core/src/tree/TreeTrainer.cpp, core/test/forest/ForestCharacterizationTest.cpp, core/test/relabeling/MultiCausalRelabelingStrategyTest.cpp, r-package/grf/bindings/MultiCausalForestBindings.cpp
This is just an aesthetic suggestion to simplify how the dimension of `responses_by_sample` is handled.
Recall `responses_by_sample(i, )` is typically length 1 for most forests, but with the introduction of a vector valued splitting rule, it may be longer, like `num_outcomes * num_treatments` for the `multi_arm_causal_forest`. 
Now TreeTrainer initializes this array with the general and more future friendly
```C++
Eigen::ArrayXXd responses_by_sample(data.get_num_rows(), relabeling_strategy->get_response_length());
```
instead of
```C++
Eigen::ArrayXXd responses_by_sample(data.get_num_rows(), data.get_num_outcomes() * data.get_num_treatments());
```
with `get_response_length()` delegated to the `RelabelingStrategy` (default value of 1, overriden by forests which wants to)
=> Simplify setting the dimension of `responses_by_sample`

r-package/grf/pkgdown/_pkgdown.yml, r-package/grf/vignettes/policy_learning.Rmd, r-package/grf/vignettes/visualize_tree.Rmd
The "visualize trees" vignette contained an example on policy learning - it seems more natural to have this in a separate vignette, added a short one here.
=> Reorganize the "visualize tree" vignette

r-package/grf/tests/testthat/test_probability_forest.R, r-package/grf/tests/testthat/test_regression_forest.R
Just adding one more test: that sample weighting is identical to replicating samples.
=> Extend probability forest test coverage

r-package/grf/R/average_treatment_effect.R
With option `TMLE` the returned vector name is `estimate.1` instead of `estimate`. `unname` the object for consistency before returning. Minor CC @swager
```R
> p <- 6
> n <- 2000
> X <- matrix(2 * runif(n * p) - 1, n, p)
> eX <- 0.25 + 0.5 * (X[, 1] > 0)
> W <- rbinom(n, 1, eX)
> TAU <- 4 * (X[, 1] > 0)
> Y <- TAU * (W - 0.5) + rnorm(n)
> forest.causal <- causal_forest(X, Y, W, num.trees = 500)
> average_treatment_effect(forest.causal, target.sample = "all", method = "AIPW")
estimate    std.err 
2.11521382 0.07102092 
> average_treatment_effect(forest.causal, target.sample = "all", method = "TMLE")
estimate.1    std.err 
2.11394668 0.06854403 
```
=> Return `unname(tau.hat)` in `average_treatment_effect` 

r-package/grf/tests/testthat/test_average_effect.R, r-package/grf/tests/testthat/test_probability_forest.R, r-package/grf/tests/testthat/test_regression_forest.R
Some minor housekeeping towards #722.
Some tests swap out `[` with `[[` because `expect_equal` expects the names of the objects compared to be the same.
(+two minor expect_equal polishes in other test cases, more can be done in separate PRs)
=> Use `expect_equal` in `test_average_effect.R`

r-package/grf/R/probability_forest.R, r-package/grf/man/probability_forest.Rd
Use same description as all forests doing sample weights in splitting+prediction.
=> Consistent sample.weight docstring in probability_forest

r-package/grf/R/local_linear_forest.R, r-package/grf/R/regression_forest.R, r-package/grf/man/predict.ll_regression_forest.Rd, r-package/grf/man/predict.regression_forest.Rd
Update @rinafriedberg's local linear forest to have the same argument description for `ll.lambda` across all forests (i.e. that it is tuned by default - copied from causal forests' local linear predict description).
=> Consistent docstring for ll.lambda 

r-package/grf/R/causal_survival_forest.R
Makes this already involved code easier to read by reducing the number of objects you need to keep track of.
=> Remove some variable definitions in causal_survival_forest

core/src/forest/ForestTrainers.cpp, core/src/forest/ForestTrainers.h, core/test/forest/ForestCharacterizationTest.cpp, r-package/grf/bindings/MultiCausalForestBindings.cpp
Heeding @jtibshirani's suggestion in #848 and omitting this redundant argument which was intended for future experimentation flexibility.
=> Remove redundant argument in multi_causal_trainer

r-package/grf/R/causal_forest.R, r-package/grf/R/instrumental_forest.R, r-package/grf/R/regression_forest.R, r-package/grf/R/tune_forest.R, r-package/grf/man/tune_forest.Rd
Just a minor aesthetic polish: use the same argument names in the internal tuning function `tune_forest` as the external arguments the callee uses. Less names to keep track of = less room for bugs.
=> Use same consistent argument names in tune_forest

core/src/prediction/PredictionValues.cpp, core/src/prediction/PredictionValues.h, r-package/grf/bindings/RcppUtilities.cpp, r-package/grf/bindings/RcppUtilities.h
Minor aesthetic: After #519 this method is not used anymore as there are no destructive iterations over forest objects.
=> Remove defunct PredictionValues.clear()

r-package/grf/R/input_utilities.R, r-package/grf/R/multi_arm_causal_forest.R, r-package/grf/R/probability_forest.R, r-package/grf/R/tune_forest.R
Since [R 3.1](https://cran.r-project.org/doc/manuals/r-release/NEWS.3.html) there is a fast vectorized alternative to `any(is.na(x))`: `anyNA(x)` (https://stat.ethz.ch/R-manual/R-patched/library/base/html/NA.html). Make use of this the few places an NA check is needed.
=> Replace any(is.na(x)) with anyNA(x)

core/src/prediction/CausalSurvivalPredictionStrategy.cpp, core/src/relabeling/CausalSurvivalRelabelingStrategy.cpp, r-package/grf/tests/testthat/test_causal_survival_forest.R
Updates sample weighted estimation for `causal_survival_forest` in accordance with #796: sample weights enter the estimating equation as sample_weight * forest_weight. (Also adds sample weighted relabeling).
1. #### MSE check: sample weighting with IPCW improves complete-data MSE
```R
summary(replicate(100, {
n <- 2000
p <- 5
X <- matrix(runif(n * p), n, p)
Y.max <- 1
failure.time <- pmin(rexp(n) * X[, 1] + W, Y.max)
censor.time <- 4 * runif(n)
Y <- round(Y, 2)
e <- 1 / (1 + exp(-4 * X[, 1]))
w <- runif(n) <= e
sample.weights <- 1 / e[w]
r.monte.carlo <- rexp(5000)
tau <- rep(NA, n)
for (i in 1:n) {
tau[i] <- mean(pmin(r.monte.carlo * X[i, 1] + 1, Y.max) -
pmin(r.monte.carlo * X[i, 1], …
```
=> Update sample weights for causal survival forest

r-package/grf/R/causal_survival_forest.R
```
> n <- 50000
> p <- 10
> X <- matrix(rnorm(n * p), n, p)
> W <- rbinom(n,1,.5)
> sf.survival <- list(X.orig=cbind(X,W))
> system.time(replicate(50, {
+   X.orig <- sf.survival[["X.orig"]]
+   sf.survival[["X.orig"]] <- cbind(X, rep(0, nrow(X)))
+   # Do something
+   sf.survival[["X.orig"]] <- X.orig
+ }))
user  system elapsed 
0.437   0.199   0.636 
> system.time(replicate(50, {
+   sf.survival[["X.orig"]][, p + 1] <- rep(0, nrow(X))
+   # Do something
+   sf.survival[["X.orig"]][, p + 1] <- W # Restore
+ }))
user  system elapsed 
0.083   0.063   0.147 
```
=> Avoid unnecessary copy in internal CSF OOB calculation

REFERENCE.md, r-package/grf/R/causal_forest.R, r-package/grf/man/causal_forest.Rd, r-package/grf/tests/testthat/test_causal_forest.R
Upcoming 2.0 release allows for making some breaking changes trimming unnecessary features: remove the `orthog.boosting` (#388) argument from `causal_forest`. No other forest has this argument, and a user can already pass custom `Y.hat` and `W.hat`.
=> Remove `orthog.boosting` argument

r-package/grf/R/causal_survival_forest.R
These two entries were missing from the survival nuisance arguments, a re-run of mse from #884:
```
summary(replicate(100, {
n <- 2000
p <- 5
X <- matrix(runif(n * p), n, p)
Y.max <- 1
failure.time <- pmin(rexp(n) * X[, 1] + W, Y.max)
censor.time <- 4 * runif(n)
Y <- round(Y, 2)
e <- 1 / (1 + exp(-4 * X[, 1]))
w <- runif(n) <= e
sample.weights <- 1 / e[w]
r.monte.carlo <- rexp(5000)
tau <- rep(NA, n)
for (i in 1:n) {
tau[i] <- mean(pmin(r.monte.carlo * X[i, 1] + 1, Y.max) -
pmin(r.monte.carlo * X[i, 1], Y.max))
}
cs.forest <- causal_survival_forest(X[w, ], Y[w], W[w], D[w], num.trees = 500)
cs.forest.weighted <- causal_survival_forest(X[w, ], Y[w], W[w], D[w], sample.weights = …
```
=> Add sample.weights/clusters to CSF nuisance args

r-package/grf/tests/testthat/test_causal_survival_forest.R
Take this .05 as an aberration:
=> Slight bump in CSF test tolerance

REFERENCE.md
This section in REFERENCE was not updated in #723, syncing it with [that](https://grf-labs.github.io/grf/reference/average_treatment_effect.html) here.
=> Update REFERENCE with latest average_treatment_effect overview

REFERENCE.md
Just some minor clarifications, as @susanne-207 pointed out this section is not exactly crystal clear.
* The header name was outdated -> "Selecting Balanced Splits"
* alpha <= 0.25 is not enforced anywhere in the code
* clarify the sentence refers to causal splitting 
* clarify this refers to the stabilize.splits=TRUE argument
=> Update stabilized split section in REFERENCE

core/src/prediction/CausalSurvivalPredictionStrategy.cpp
This line should come after the check if weights are zero.
=> Move prediction allocation in CSF

r-package/grf/tests/testthat/test_average_effect.R, r-package/grf/tests/testthat/test_causal_forest.R, r-package/grf/tests/testthat/test_causal_survival_forest.R, r-package/grf/tests/testthat/test_forest_summaries.R, r-package/grf/tests/testthat/test_multi_arm_causal_forest.R, r-package/grf/tests/testthat/test_quantile_forest.R, r-package/grf/tests/testthat/test_regression_forest.R, r-package/grf/tests/testthat/test_survival_forest.R
Explicitly pass argument `tolerance`, as `tol` is an undocumented alias in expect_equal.
=> Use tolerance instead of tol alias

core/src/prediction/ObjectiveBayesDebiaser.cpp
In the very unlikely event the pointwise variance is zero `ObjectiveBayesDebiaser::debias` will return NaN instead of zero because of a division by 0.
```
> set.seed(4)
> n = 100; p = 5
> X = matrix(rnorm(n*p), n, p)
> Y = rep(10, n)
> Y[1:2] = 20
> rf = regression_forest(X, Y)
> predict(rf, estimate.variance = TRUE)$variance.estimates
[1]          NaN          NaN 1.084467e-03 6.803920e-04 1.847954e-03 4.816733e-03 8.203224e-01 4.293588e-04
[9] 1.829098e-04 1.900269e-05 5.725878e-04 5.007151e-04 4.442478e-04 2.015354e+00 9.222246e-04 6.571535e-03
[17] 4.125939e-05 1.849286e-01 6.999847e-04 4.101375e-03 8.153235e-04 6.298040e-02 2.201760e-04 2.345587e-04
[25] 5.584594e-04 7.875910e-01 3.903191e-04 2.584297e-02 1.033622e-03          NaN 6.820829e-02 7.781560e-04
[33] 6.627194e-02 …
```
=> Return zero in case variance is zero

core/third_party/optional/optional.hpp
The bundled header-only [optional](https://github.com/martinmoene/optional-lite) library can be upgraded before GRF 2.0. Attaching the latest https://github.com/martinmoene/optional-lite/releases/tag/v3.4.0
=> Upgrade bundled optional library 3.1.1 -> 3.4.0

core/src/prediction/MultiCausalPredictionStrategy.cpp
These two matrix expressions does not exhibit aliasing and can avoid a copy.
=> Add noalias to outer product in MultiCausalPredictionStrategy

core/src/relabeling/CausalSurvivalRelabelingStrategy.cpp, core/src/relabeling/InstrumentalRelabelingStrategy.cpp, core/src/relabeling/LLRegressionRelabelingStrategy.cpp, core/src/relabeling/NoopRelabelingStrategy.cpp, core/src/relabeling/QuantileRelabelingStrategy.cpp, core/src/splitting/CausalSurvivalSplittingRule.cpp, core/src/splitting/InstrumentalSplittingRule.cpp, core/src/splitting/ProbabilitySplittingRule.cpp, core/src/splitting/RegressionSplittingRule.cpp, core/src/splitting/SurvivalSplittingRule.cpp
The shortcut `operator()(Index index)` for arrays is not crystal clearly [documented](https://eigen.tuxfamily.org/dox/classEigen_1_1DenseCoeffsBase_3_01Derived_00_01ReadOnlyAccessors_01_4.html#af9fadc22d12e48c82745dad534a1671a) and appear to rely on logic that can be [deprecated](https://eigen.tuxfamily.org/dox/group__flags.html#ga4b983a15d57cd55806df618ac544d09e).
Switch to accessing `responses_by_sample` with `(sample, 0)` in all single-response forests for future proofness.
=> Access single-variable responses_by_sample with (sample, 0) instead of (sample)

r-package/grf/bindings/AnalysisToolsBindings.cpp, r-package/grf/bindings/CausalForestBindings.cpp, r-package/grf/bindings/CausalSurvivalForestBindings.cpp, r-package/grf/bindings/InstrumentalForestBindings.cpp, r-package/grf/bindings/MultiCausalForestBindings.cpp, r-package/grf/bindings/MultiRegressionForestBindings.cpp, r-package/grf/bindings/ProbabilityForestBindings.cpp, r-package/grf/bindings/QuantileForestBindings.cpp, r-package/grf/bindings/RcppUtilities.cpp, r-package/grf/bindings/RcppUtilities.h, r-package/grf/bindings/RegressionForestBindings.cpp, r-package/grf/bindings/SurvivalForestBindings.cpp, r-package/grf/src/RcppExports.cpp
Rcpp data types are already light wrappers, however stick with this C++ idiom to keep it crystal clear no data is modified.
Training/test data in R is already copied when the data matrices are created in the input utilities (where all data is copied into a contiguous chunk)
=> Pass all Rcpp training/test data as const reference

r-package/grf/R/boosted_regression_forest.R, r-package/grf/R/causal_forest.R, r-package/grf/R/causal_survival_forest.R, r-package/grf/R/instrumental_forest.R, r-package/grf/R/ll_regression_forest.R, r-package/grf/R/multi_arm_causal_forest.R, r-package/grf/R/multi_regression_forest.R, r-package/grf/R/probability_forest.R, r-package/grf/R/quantile_forest.R, r-package/grf/R/regression_forest.R, r-package/grf/R/survival_forest.R, r-package/grf/man/boosted_regression_forest.Rd, r-package/grf/man/causal_forest.Rd, r-package/grf/man/causal_survival_forest.Rd, r-package/grf/man/instrumental_forest.Rd, r-package/grf/man/ll_regression_forest.Rd, r-package/grf/man/multi_arm_causal_forest.Rd, r-package/grf/man/multi_regression_forest.Rd, r-package/grf/man/probability_forest.Rd, r-package/grf/man/quantile_forest.Rd, r-package/grf/man/regression_forest.Rd, r-package/grf/man/survival_forest.Rd
Hyperlinking directly to section is flaky and may go stale, as this one evidently did. Remove alltogheter.
=> Remove docstring hyperlink

r-package/grf/DESCRIPTION, r-package/grf/R/survival_forest.R, r-package/grf/man/predict.survival_forest.Rd, r-package/grf/man/survival_forest.Rd
Add a docstring example on how to calculate an error rate based on concordance, using the optional `survival` package.
We delegate to this package since it facilitates easy comparison between any other method, as the exact handling of ties etc may vary between definitions (to compare with for example randomForestSRC just replace `chf.score` with `rowSums(forest.src$chf)`). `survival` (@therneau) also does it efficiently in O(nlogn) time, which would be a non-trivial addition to grf.
The docstring example uses survival predictions based on the mortality score suggested in Ishwaran (2008) section 4.1, which is the sum of the cumulative hazard function.
We can add this as a separate GRF function calling into `survival` in a future release pending user interest.
=> Add a concordance example to docstring

r-package/grf/R/RcppExports.R, r-package/grf/R/survival_forest.R, r-package/grf/bindings/SurvivalForestBindings.cpp, r-package/grf/src/RcppExports.cpp, r-package/grf/tests/testthat/test_survival_forest.R
In the event the forest was trained with sample weights, they where accidentally omitted when calling predict on a test set or oob with precompute set to false.
=> Fix survival_forest test set predictions with sample weights

core/src/prediction/collector/DefaultPredictionCollector.cpp
This makes the behavior of `DefaultPredictionCollector` and `OptimizedPredictionCollector` identical in the case when computed predictions are empty.
The (rare) use case is if a `DefaultPredictionStrategy` decides to return nothing, such as when the sum of case sample weights in a leaf is zero (which can be the case for `SurvivalPredictionStrategy`.
=> Account for empty predictions in DefaultPredictionCollector

core/src/prediction/SurvivalPredictionStrategy.cpp
In the rare event all sample weights for a test sample sum to zero, return empty predictions. This mimics behavior of other forests implementing sample weighted predictions.
=> survival_forest: return placeholder predictions when all sample weights = 0

r-package/grf/R/dgps.R
Don't mix one-colum matrix and vectors.
=> Consistent return types in generate_causal_data

core/test/splitting/MultiCausalSplittingRuleTest.cpp
Just bumping up some test coverage by repeating this splitting test on the first `{500, 250, 113, 25, 10, 3}` samples in addition of doing it on the full data.
=> Extend MultiCausalSplittingRule tests

r-package/grf/R/multi_arm_causal_forest.R
Ensures colnames are syntactically valid (no duplicates, no leading _,...)
=> Use make.names for colnames

r-package/grf/R/average_treatment_effect.R, r-package/grf/R/get_scores.R, r-package/grf/R/multi_arm_causal_forest.R, r-package/grf/man/average_treatment_effect.Rd, r-package/grf/man/get_scores.multi_arm_causal_forest.Rd, r-package/grf/man/multi_arm_causal_forest.Rd, r-package/grf/man/predict.multi_arm_causal_forest.Rd, r-package/grf/tests/testthat/test_multi_arm_causal_forest.R
As discussed with @halflearned, re-design ATE output for multiple treatments. For a binary treatment, access with `[[` allows it to be a drop-in replacement for causal_forest. 
```R
n <- 500
p <- 10
W <- as.factor(sample(c("A", "B", "C"), n, replace = TRUE))
Y1 <- X[, 1] + X[, 2] * (W == "B") - 1.5 * X[, 2] * (W == "C") + rnorm(n)
Y2 <- X[, 2] + X[, 3] * (W == "B") - 1.5 * X[, 4] * (W == "C") + rnorm(n)
mc.forest <- multi_arm_causal_forest(X, cbind(Y1=Y, Y2=Y2), W)
average_treatment_effect(mc.forest)
mc.forest <- multi_arm_causal_forest(X, Y1, W)
average_treatment_effect(mc.forest)
(note by default R makes the rownames of the DF equal to `contrast` when suitable (i.e. one outcome), allowing a convenient `ate["contrast", "estimate"]` access.)
```
This …
=> Update MGRF API

r-package/grf/tests/testthat/test_instrumental_forest.R
#774 removed a `set.seed` (bad practice) from this test case, bump tolerance in line with the expected worse case behavior:
```
library(grf)
library(testthat)
set.seed(123)
res=replicate(50, {
p <- 6
n <- 2000
n.test <- 2000
eps <- rnorm(n)
Z <- rbinom(n, 1, 2 / 3)
filter <- rbinom(n, 1, 1 / (1 + exp(-1 * eps)))
W <- Z * filter
tau <- apply(X[, 1:2], 1, function(xx) sum(pmax(0, xx)))
mu <- apply(X[, 2 + 1:2], 1, function(xx) sum(pmax(0, xx)))
Y <- (2 * W - 1) / 2 * tau + mu + eps
X.test <- matrix(rnorm(n.test * p), n.test, p)
tau.true <- apply(X.test[, 1:2], 1, function(xx) sum(pmax(0, xx)))
forest.iv <- instrumental_forest(X, Y, W, Z, num.trees = 4000)
preds.iv.oob <- predict(forest.iv, estimate.variance = TRUE)
preds.iv <- predict(forest.iv, X.test, …
```
=> Bump instrumental_forest test tolerance

DEVELOPING.md
This was only a convenience since the previous major release lingered around in development mode for almost a year.
=> Remove 4 digit release note

core/test/forest/ForestSmokeTest.cpp
Avoid the catch clause's warning in ForestSmokeTest.cpp:
```  D:\a\1\s\core\test\forest\ForestSmokeTest.cpp(108,38): warning C4101: 'e': unreferenced local variable [D:\a\1\s\core\build\grf.vcxproj]```
with the idiom from https://groups.google.com/g/mongodb-user/c/C97StGxNIow
=> Avoid `unreferenced variable` MSVC warning

core/src/forest/ForestTrainer.cpp, core/src/prediction/MultiCausalPredictionStrategy.cpp, core/src/prediction/ProbabilityPredictionStrategy.cpp, core/src/prediction/SurvivalPredictionStrategy.cpp, core/src/prediction/collector/DefaultPredictionCollector.cpp, core/src/prediction/collector/OptimizedPredictionCollector.cpp, core/src/prediction/collector/TreeTraverser.cpp, core/src/relabeling/QuantileRelabelingStrategy.cpp, core/src/sampling/RandomSampler.cpp, core/src/splitting/CausalSurvivalSplittingRule.cpp, core/src/splitting/MultiRegressionSplittingRule.cpp, core/src/splitting/ProbabilitySplittingRule.cpp, core/src/splitting/RegressionSplittingRule.cpp, core/src/splitting/SurvivalSplittingRule.cpp
Only aesthetic update for GRF: address some MSVC warnings - explicitly declare type conversions in order to be good C++ citizen. Related issue: #231 
(A future PR could replace other old C-style casts with modern C++ static_casts)
=> Convert implicit to explicits casts

r-package/grf/R/get_scores.R
See #1020. This affects the standard error output of `average_treatment_effect`.
For the GRF 2.0.2 CRAN release, correct AIPW standard errors can be obtained by using `policytree`'s `double_robust_scores` method, which is correct, see #1020.
<details>
<summary>Re-run of the included gist by @halflearned:</summary>
```
library(grf)
set.seed(1)
n <- 1000
p <- 7
make_data <- function(n, p) {
X <- round(matrix(rnorm(n*p), n, p), 2)
mu <- c(1,2,3)
mu.all <- matrix(mu, nrow=n, ncol=3, byrow=TRUE)
W <- factor(sample(3, size=n, replace=TRUE), levels=seq(1, 3))
Y <- mu.all[cbind(1:n, W)] + rnorm(n)
list(X=X, W=W, Y=Y, mu=mu, mu.all=mu.all)
}
tab <- do.call(rbind, lapply(seq(500), function(i) {
print(i)
data <- make_data(n, p)
X <- data$X
W <- data$W
Y <- data$Y
delta.truth <- data$mu[-1] - …
```
=> Fix `multi_arm_causal_forest` IPW calculation

r-package/grf/R/survival_forest.R, r-package/grf/man/survival_forest.Rd
Fix minor notation inconsistency with the notation used in the CSF paper.
=> Fix documentation notation in survival_forest

r-package/grf/R/survival_forest.R, r-package/grf/man/survival_forest.Rd, r-package/grf/tests/valgrind/test_grf_valgrind.R
Place more restrictions on input Y (allowing this to be negative may lead to bugs in `causal_survival_forest` and is not that intuitive).
=> Require non-negative events in survival

r-package/grf/R/causal_survival_forest.R, r-package/grf/R/survival_forest.R, r-package/grf/man/causal_survival_forest.Rd, r-package/grf/man/survival_forest.Rd
Add a docstring note that on survival data with very low event rate the `alpha` parameter may need to be lowered to get the forest to split.
Does this look good to you @CrystalXuR?
As point of reference a causal forest with very low treatment propensity will also not split due to the split stabilizing criteria, which is kind of expected behavior.
For survival/causal survival we can keep this documentation note for now and instead elaborate on empirical examples in a future survival Vignette (omit having some automated message for now, as very low event rate data is a special use case it is reasonable to expect a user to think about)
=> Add note on low event rate to docstring

REFERENCE.md
The Algorithm Reference has lagged a bit behind the latest additions.
Add a brief description of `multi_arm_causal_forest` at the end of the Causal Forests section in the [REFERENCE](https://grf-labs.github.io/grf/REFERENCE.html) in the same style as the rest of the document.
=> Add brief multi-arm causal forest description to REFERENCE

DEVELOPING.md
Add a convenient TOC (and logo) to DEVELOPING keeping it as organized as REFERENCE.
=> Add TOC to DEVELOPING.md

core/src/forest/ForestOptions.cpp
ForestOptions uses `seed=0` as sentinel to mean "pick a seed at random for the forest". This has unintended consequences for R users, see #1091.
Let's check that @jtibshirani is fine with this before merging.
(closes #1091)
=> Remove "legacy" sentinel seed in ForestOptions

r-package/grf/R/multi_arm_causal_forest.R
* Make W.hat/Y.hat input check more robust, but "silently" allow data.frame as well as matrix for consistency, since that is the behavior for X and Y
* Print a warning if W.hat is provided with column names and they do not correspond to the treatment levels W
(closes #1096)
=> Extend multi arm causal forest input checks

r-package/grf/R/average_treatment_effect.R
ATE estimates does not take sample weights into account when using TMLE: explicitly disable this code path instead of silently ignoring them.
=> Disable sample weights for TMLE ATE

r-package/grf/R/average_treatment_effect.R, r-package/grf/tests/testthat/test_average_effect.R
As pointed out by @davidahirshberg, an old typo caused optional sample weights not to be taken into account during SE calculation for ATT/ATC when clusters not supplied.
This only affects `average_treatment_effect` uses cases where method="AIPW", and target.sample = "treated" or "control" and the forest is trained with sample.weights and no clusters.
This PR also updates the finite sample correction n/(n-1) when some some weights are zero. A follow-up PR address the same thing for AIPW and target.sample="all" where we rely on similarly hand computed SEs
=> Fix sample weighted ATT/ATC standard errors

r-package/grf/R/forest_summary.R, r-package/grf/man/test_calibration.Rd
Just adding a quick reference to `rank_average_treatment_effect` as discussed with @swager
=> Refer to RATE in test_calibration

r-package/grf/R/tune_forest.R
Revert to default parameters if DiceKringing extrapolates optimal parameters outside range of admissible draws, as can be the case when it selects a too small sample.fraction when clusters are specified, leading zero samples to be drawn. Follow up to #1067...
=> Revert to default if tuning selects params outside valid range

r-package/grf/R/survival_forest.R, r-package/grf/man/predict.survival_forest.Rd, r-package/grf/tests/testthat/test_survival_forest.R
Closes #1131: fix argument failure.times s.t. it it predicts new time points on the existing curve, w/o snapping a new curve onto the grid. This does not affect `causal_survival_forest`
=> Update failure.times argument in predict.survival_forest

r-package/grf/R/survival_forest.R, r-package/grf/man/predict.survival_forest.Rd, r-package/grf/tests/testthat/test_survival_forest.R
By default (prediction.times = "curve") survival forest predicts the survival curve specified by grid failure.times for each sample Xi.
If prediction.times = "times" then it will predict the event time on the survival curve specified by failure.times[i] for each sample Xi. For example, prediction.times = pmin(Y, t0) will predict P(T > pmin(Yi, t0) | Xi)
=> Add optional argument prediction.times to survival_forest.predict

r-package/grf/tests/testthat/test_forest_summaries.R, r-package/grf/tests/testthat/test_rank_average_treatment.R
Small fix affecting a few tests.
> all.equal.numeric() gains a sanity check on its tolerance
argument - calling all.equal(a, b, c) for three numeric vectors
is a surprisingly common error.
https://stat.ethz.ch/pipermail/r-announce/2022/000683.html
=> Update vector arg calls to expect_equal

REFERENCE.md
After explaining grf to several people: the role of the R-learner wasn't clear to many people, including stats phds, so adding an explicit mention to the reference
=> Add R-learner mention to REFERENCE

DEVELOPING.md
Now that GitHub markdown is supposed to support LaTeX: adding an explanation of how the OptimizedPredictionStrategy works to the developing docs. Last time we touched sample weights we wrote up a pdf https://github.com/grf-labs/grf/pull/774, it would be convenient to record this in DEVELOPING for easier future reference.
=> Add sufficient statistics note to DEVELOPING

r-package/grf/R/causal_survival_forest.R, r-package/grf/R/get_scores.R
This is only an aesthetic change. The way CSF R updated the score was overly involved and more verbose than in the relabeling strategy. Simplify it and make it consistent.
=> Simplify CSF DR score

core/src/prediction/CausalSurvivalPredictionStrategy.cpp, core/src/relabeling/CausalSurvivalRelabelingStrategy.cpp, r-package/grf/R/causal_survival_forest.R, r-package/grf/R/get_scores.R, r-package/grf/tests/testthat/test_causal_survival_forest.R
Purely aesthetic: use consistent naming convention from CSF paper to make it easier to connect the CSF paper to its implementation (#1175).
=> Use consistent internal CSF variable names

r-package/grf/R/ll_regression_forest.R
Allow ll_regression_forest input to work regardless of X type when enable.ll.split = TRUE.
Fixes #1197 (thanks to @tmieno2 for pointing this out)
=> Fix overall.beta calculation when X is not matrix

r-package/grf/pkgdown/_pkgdown.yml, r-package/grf/vignettes/ate_transport.Rmd
Add a vignette defining and explaining a function `average_treatment_effect_test` users can copy/paste for this purpose.
Perf of the vignette example:
```
res <- replicate(500, {
n <- 2000
p <- 5
X.population <- matrix(rnorm(n * p), n, p)
trial.inclusion.prob <- 1 / (1 + exp(-X.population[, 1] / 2))
S <- rbinom(n, 1, trial.inclusion.prob)
X.test <- X.population[S == 0, ]
X <- X.population[S == 1, ]
W <- rbinom(nrow(X), 1, 0.5)
tau <- X[, 1] + 1
Y <- X[, 2] + tau * W + rnorm(nrow(X))
forest <- causal_forest(X, Y, W, W.hat = 0.5)
estimate <- average_treatment_effect_test(forest, X.test)
estimate.true <- mean(X.test[, 1] + 1)
c(bias.dr = estimate[[1]] - estimate.true,
coverage.dr = abs(estimate[[1]] - estimate.true) / estimate[[2]] <= 1.96,
bias.plain = mean(predict(forest, …
```
=> Add vignette on estimating ATE on test set

r-package/grf/R/rank_average_treatment.R, r-package/grf/man/rank_average_treatment_effect.Rd
Just fixing a tiny docstring example subset operation that was incorrect.
=> Fix subset typo in RATE docstring

r-package/grf/R/rank_average_treatment.R
Just a minor fix: passing `priorities` with missing values is fine as long as `subset = those with non-missing values`.
=> Move NA check in RATE

r-package/grf/R/forest_summary.R, r-package/grf/man/best_linear_projection.Rd
Minor fix which allows a user to pass an arbitrary data.frame `A` and have it behave as calling `lm` directly (that is, it will expand factor variables if present).
=> Remove as.matrix in best_linear_projection

r-package/grf/R/causal_survival_forest.R, r-package/grf/R/survival_forest.R, r-package/grf/man/causal_survival_forest.Rd, r-package/grf/man/predict.causal_survival_forest.Rd, r-package/grf/man/predict.survival_forest.Rd, r-package/grf/man/survival_forest.Rd
Do some minor enhancements to survival docstrings by highlighting the role of the event grid, removing some unnecessary examples, + add CI example in CSF.
=> Clarify event grids in survival docstrings

azure-pipelines.yml
The valgrind in ubuntu-latest breaks with clang (#1248). Use ubuntu-20 for now.
=> Use ubuntu-20.04 in clang/cpp checks

r-package/grf/R/causal_survival_forest.R
CSF predicts some nuisance estimates using a "compute.oob.predictions=FALSE" workaround to get OOB estimates. This requires re-computing from C++ and should take the same num.threads as the training forest: Fixed in this PR. (Should not affect any other forest where nuisance estimates are `predicted` afterwards since these all use precomputed training OOB).
See #1266 and thanks to @kcgthb and @janewliang for pointing out.
=> Use num.threads in CSF nuisance predictions

r-package/grf/R/forest_summary.R, r-package/grf/man/best_linear_projection.Rd, r-package/grf/tests/testthat/test_average_effect.R, r-package/grf/tests/testthat/test_forest_summaries.R
Add option `target.sample = c("all", "overlap")` to `best_linear_projection` which uses estimates of propensity scores to compute a BLP with weights = e(x)(1 - e(x)).
Until the next cran release: to use this option without recompiling grf from scratch, `source`-able [best_linear_projection.R](https://gist.github.com/erikcs/424b7ac84e7360d755760ca597d82d6e)
=> Add "overlap" option to best_linear_projection

r-package/grf/R/get_scores.R, r-package/grf/R/multi_arm_causal_forest.R, r-package/grf/R/multi_regression_forest.R, r-package/grf/man/get_scores.multi_arm_causal_forest.Rd, r-package/grf/man/multi_arm_causal_forest.Rd, r-package/grf/man/predict.multi_arm_causal_forest.Rd, r-package/grf/man/predict.multi_regression_forest.Rd
`predict.multi_arm_causal_forest` by default returns an array with dimensions num.samples * num.arms - 1 * num.outcomes. Add an optional argument (FALSE by default) that drops this singleton dimension for cases when the forest is fit with one outcome.
=> Add optional drop argument to predict.mgrf

r-package/grf/R/causal_survival_forest.R, r-package/grf/R/get_scores.R, r-package/grf/man/causal_survival_forest.Rd, r-package/grf/man/get_scores.causal_survival_forest.Rd, r-package/grf/tests/testthat/test_causal_survival_forest.R
The reason CSF was restricted to a binary W was for simplicity, it simplifies nuisance estimation. In principle there is nothing preventing the CSF construction from being applied in the continuous exposure setting, the estimand and interpretation follows from causal forest.
This PR makes no changes to the case when W is binary. When W is continuous an additional survival forest is used to estimate m(x) = E[f(T) | X].
=> Allow continuous treatment in causal_survival_forest

core/third_party/optional/optional.hpp
Attaching the latest header-only optional library from https://github.com/martinmoene/optional-lite/releases/tag/v3.5.0
=> Upgrade bundled optional library 3.4.0 -> 3.5.0

README.md, azure-pipelines.yml, r-package/grf/bindings/Makevars
Update for latest CRAN
>Result: NOTE
Specified C++11: please drop specification unless essential
We drop this requirement in src/Makevars, but add extra tests in Azure that make sure grf R runs with all C++ versions up to C++20.
The core/ tests are kept the same as before using CXX_STANDARD 11 in CMakeLists. Can revisit that later, note that the bundled Eigen may need to be updated to make the compiler emit less warnings.
=> Drop CXX_STD in R Makevars

README.md, core/third_party/random/README.md, experiments/README.md, r-package/grf/vignettes/grf_guide.Rmd, r-package/grf/vignettes/rate.Rmd, releases/CHANGELOG.md
This PR provides necessary updates to URL references across the repository's documentation (`.md`, `.Rmd` files) for enhanced reliability and standardization. It primarily targets broken links and links that have been moved, replacing them with accurate, secure, and more stable URL references.
Details of the changes are as follows:
- ATW19 paper link update: The old link to this paper, which used an obsolete domain name, has been replaced with its permanent DOI link. The previous URL now redirects to an irrelevant site, thus this update ensures that users are directed to the correct resource.
- HTTP to HTTPS Updates: Several links that were previously using the HTTP protocol have been updated to HTTPS. While these links were being auto-redirected, this change ensures better security and …
=> Update and standardize URLs across documentation for enhanced reliability

core/src/prediction/SurvivalPredictionStrategy.h
Adding a note for future consideration: one reason Causal Survival Forest can be time consuming on large data is fitting (predicting) survival and censoring curves.
A big time chunk is spent in predicting the survival curves via the DefaultPredictionStrategy. We were aware of this when making it, just documenting it here in case we wish to revisit it in the future, it would be possible to speed up CSF by
- having survival forest use OptimizedPredictionStrategy at a higher memory cost
- have survival forest use some hash table other than the std library that is optimized for dense data
=> Add performance note to SurvivalPredictionStrategy.h

r-package/grf/R/input_utilities.R
Accidentally passing sample weights with missing entries or for example 1 / 0 (as could happen if estimating inverse weights with kaplan-meier, which may yield estimates exactly = 0) went through previously. Adding a more stringent input check to prevent this - as this could be a rare occurrence when passing estimated weights to grf.
=> Enhance input validation for sample weights

r-package/grf/vignettes/maq.Rmd
It's easier to just drop this note, makes it easier to read.
=> Remove appendix from maq vignette

r-package/grf/vignettes/grf_guide.Rmd
Hello! The documentation in this package is phenomenal. I was reviewing the guided tour and I think you meant to say relaxing assumption 2 in this line instead of assumption 1 (apologies if I am mistaken).
=> minor typo (?) in guided tour

images/logo/README.md
Consolidating some information that we previously kept on Quip.
=> Add grf logo/swag info to GitHub

r-package/grf/R/input_utilities.R
This is just to provide more informative feedback in case of accidentally indexing with an empty set in the feature matrix.
```R
n <- 500
p <- 5
Y <- pmax(X[, 1], 0) * W + X[, 2] + pmin(X[, 3], 0) + rnorm(n)
cf <- causal_forest(X[, 0], Y, W)
print(cf)
Error in raw[, feature.indices, drop = FALSE] : subscript out of bounds
predict(cf, X[, 0)
segfault
```
=> Check for non-zero dims in feature matrix

r-package/grf/R/rank_average_treatment.R
Relaxing this effective sample size check to allow as few as n = 2 clusters, which is consistent with average_treatment_effect.
=> Relax sample size requirement in boot_grf

core/CMakeLists.txt
From the [azure build](https://dev.azure.com/grf-labs/grf/_build/results?buildId=2457&view=logs&j=4ca8cba6-7183-564e-ab5e-f9751ebd5d9f&t=89a15387-052c-5742-0e51-6ee512ec3a14)
>CMake Deprecation Warning at CMakeLists.txt:2 (cmake_minimum_required):
Compatibility with CMake < 3.5 will be removed from a future version of
CMake.
>
>Update the VERSION argument <min> value or use a ...<max> suffix to tell
CMake that the project does not need compatibility with older versions.
=> Update CMake minimum to 3.5

.github/workflows/pages.yml, azure-pipelines.yml
Address some github deprecations and deploy gh-pages using actions:
>After June 30, 2024, Pages sites will require GitHub Actions for the Jekyll build step. To prevent any disruption, please enable GitHub Actions for this repository
=> Move pages to github actions

r-package/grf/DESCRIPTION, r-package/grf/R/causal_forest.R, r-package/grf/R/causal_survival_forest.R, r-package/grf/R/instrumental_forest.R, r-package/grf/R/ll_regression_forest.R, r-package/grf/R/multi_arm_causal_forest.R, r-package/grf/R/multi_regression_forest.R, r-package/grf/R/probability_forest.R, r-package/grf/R/quantile_forest.R, r-package/grf/R/regression_forest.R, r-package/grf/R/survival_forest.R, r-package/grf/man/causal_forest.Rd, r-package/grf/man/causal_survival_forest.Rd, r-package/grf/man/instrumental_forest.Rd, r-package/grf/man/ll_regression_forest.Rd, r-package/grf/man/multi_arm_causal_forest.Rd, r-package/grf/man/multi_regression_forest.Rd, r-package/grf/man/probability_forest.Rd, r-package/grf/man/quantile_forest.Rd, r-package/grf/man/regression_forest.Rd, r-package/grf/man/survival_forest.Rd
=> Add `seed` note on `num.threads` cross-platform dependency

r-package/grf/DESCRIPTION, r-package/grf/R/causal_forest.R, r-package/grf/R/causal_survival_forest.R, r-package/grf/R/instrumental_forest.R, r-package/grf/R/ll_regression_forest.R, r-package/grf/R/multi_arm_causal_forest.R, r-package/grf/R/multi_regression_forest.R, r-package/grf/R/probability_forest.R, r-package/grf/R/quantile_forest.R, r-package/grf/R/regression_forest.R, r-package/grf/R/survival_forest.R, r-package/grf/man/causal_forest.Rd, r-package/grf/man/causal_survival_forest.Rd, r-package/grf/man/instrumental_forest.Rd, r-package/grf/man/ll_regression_forest.Rd, r-package/grf/man/multi_arm_causal_forest.Rd, r-package/grf/man/multi_regression_forest.Rd, r-package/grf/man/probability_forest.Rd, r-package/grf/man/quantile_forest.Rd, r-package/grf/man/regression_forest.Rd, r-package/grf/man/survival_forest.Rd
=> Revert "Add `seed` note on `num.threads` cross-platform dependency"

core/third_party/optional/optional.hpp
Attaching the latest header-only optional library from https://github.com/martinmoene/optional-lite/releases/tag/v3.6.0
=> Upgrade bundled optional library 3.5.0 -> 3.6.0

r-package/grf/tests/testthat/test_lm_forest.R
For the invariance we care about here, then technically p has to be 1. See #1452.
=> Relax lm_forest invariance

r-package/grf/R/multi_arm_causal_forest.R, r-package/grf/man/multi_arm_causal_forest.Rd
Was recently reminded by @apoorvalal that reminding the user of AIPW might be useful.
=> Mention doubly robust ATE in mgrf docstring

r-package/grf/vignettes/diagnostics.Rmd
This PR is about a method proposed in the tutorial, [Evaluating a causal forest fit](https://grf-labs.github.io/grf/articles/diagnostics.html). 
One heuristic method to detect heterogeneity described in the tutorial over-rejects under the null, I believe due to the winner's curse. (The same model is used to determine subgroups and implement estimation). Cross-fitting resolves this problem, and I have proposed a small modification to the tutorial that provides this suggestion in this pull-request.
=> Clarify diagnostics vignette
